### ISSUE TITLE
First Request to Reactive SQL fail

### ISSUE THREAD

**Issue by hernael** [quarkusio/quarkus#14709]
**Describe the bug**
at first time that request an concurrency reactive sql client, it fail.
But the second time it work fine

**Expected behavior**
that also works fine the first time

**Actual behavior**
after the application startup and receives the first request to a method with reactive sql concurrent calls, the connection fail.

**To Reproduce**
In a Reactive SQL Cient Application with resteasy,reactive-pg-client,resteasy-mutiny extensions
1. create a methos like this:

```
var query = findAll();
var list = query.page(Page.of(1, 10)).list();
var total = query.count();

return Uni.combine().all().unis(list, total).asTuple().onItem().transform((tuple) -> {
    return PageResponse.newBuilder().setElements(tuple.getItem1()).setTotalCount(tuple.getItem2()).build();
});
```

2. statup quarkus
3. genered an request
4. this will fail on the line "var total = query.count();"

The error is:

```
Caused by: java.lang.IllegalStateException: session is currently connecting to database
	at org.hibernate.reactive.pool.impl.ProxyConnection.withConnection(ProxyConnection.java:52)
	at org.hibernate.reactive.pool.impl.ProxyConnection.selectJdbc(ProxyConnection.java:109)
	at org.hibernate.reactive.loader.ReactiveLoader.executeReactiveQueryStatement(ReactiveLoader.java:106)
	at org.hibernate.reactive.loader.ReactiveLoader.doReactiveQueryAndInitializeNonLazyCollections(ReactiveLoader.java:63)
	at org.hibernate.reactive.loader.CachingReactiveLoader.doReactiveList(CachingReactiveLoader.java:62)
	at org.hibernate.reactive.loader.CachingReactiveLoader.reactiveListIgnoreQueryCache(CachingReactiveLoader.java:80)
	at org.hibernate.reactive.loader.hql.impl.ReactiveQueryLoader.reactiveList(ReactiveQueryLoader.java:113)
	at org.hibernate.reactive.loader.hql.impl.ReactiveQueryLoader.reactiveList(ReactiveQueryLoader.java:87)
	at org.hibernate.reactive.session.impl.ReactiveQueryTranslatorImpl.reactiveList(ReactiveQueryTranslatorImpl.java:122)
	at org.hibernate.reactive.session.impl.ReactiveHQLQueryPlan.performReactiveList(ReactiveHQLQueryPlan.java:114)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$reactiveList$6(ReactiveSessionImpl.java:389)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.reactiveList(ReactiveSessionImpl.java:389)
	at org.hibernate.reactive.session.impl.ReactiveQueryImpl.doReactiveList(ReactiveQueryImpl.java:133)
	at org.hibernate.reactive.session.impl.ReactiveQueryImpl.getReactiveResultList(ReactiveQueryImpl.java:109)
	at org.hibernate.reactive.session.impl.ReactiveQueryImpl.getReactiveSingleResult(ReactiveQueryImpl.java:84)
	at org.hibernate.reactive.mutiny.impl.MutinyQueryImpl.getSingleResult(MutinyQueryImpl.java:168)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.lambda$count$3(CommonPanacheQueryImpl.java:204)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.applyFilters(CommonPanacheQueryImpl.java:323)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.count(CommonPanacheQueryImpl.java:204)
	at io.quarkus.hibernate.reactive.panache.runtime.PanacheQueryImpl.count(PanacheQueryImpl.java:144)
	at com.example.template.repository.reactive.panache.CotPanacheRepository.getPage(CotPanacheRepository.java:46)
	at com.example.template.repository.reactive.panache.CotPanacheRepository_ClientProxy.getPage(CotPanacheRepository_ClientProxy.zig:1614)
	at com.example.template.core.impl.CotCoreImpl.getPage(CotCoreImpl.java:37)
	at com.example.template.core.impl.CotCoreImpl_ClientProxy.getPage(CotCoreImpl_ClientProxy.zig:349)
	at com.example.template.api.CotApi.getPage(CotApi.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	... 25 more
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.3.18-lp152.60-default x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5, 1.11.0 and 1.11.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Comment by hernael** [comment]
yes thanks! the full log is:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.example.template:template-core >-------------
[INFO] Building template-core 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.11.1.Final:dev (default-cli) @ template-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 68 source files to /home/hernael/template/template-core/target/classes
Listening for transport dt_socket at address: 5005
2021-01-29 17:18:48,310 INFO  [org.jbo.threads] (main) JBoss Threads version 3.2.0.Final
2021-01-29 17:18:48,416 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor#config threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value database.url in property quarkus.datasource.reactive.url
	at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:44)
	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:37)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:18)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:192)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:149)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:209)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.config(ConfigEditorProcessor.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:308)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:182)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:59)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:78)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:372)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:128)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:81)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor#config threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value database.url in property quarkus.datasource.reactive.url
	at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:44)
	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:37)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:18)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:192)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:149)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:209)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.config(ConfigEditorProcessor.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:153)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:306)
	... 9 more
Caused by: java.util.NoSuchElementException: SRCFG00011: Could not expand value database.url in property quarkus.datasource.reactive.url
	at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:44)
	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:37)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:18)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:192)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:149)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:209)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.config(ConfigEditorProcessor.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2021-01-29 17:18:48,416 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure

```

**Comment by DavideD** [comment]
I'm having a look

**Comment by DavideD** [comment]
Is there a test project somewhere that I can look at?

**Comment by hernael** [comment]
not yet, but it is easy to reproduce. Only make two concurrent reactive request to database (postgresql 13 in my case), startup the application and execute a reactive service.
If you wish i could create a demo test repo

**Comment by DavideD** [comment]
> If you wish i could create a demo test repo

That would be great and save me a lot of time

**Comment by hernael** [comment]
ok, give me about 10 min

**Comment by DavideD** [comment]
Thanks

**Comment by Sanne** [comment]
This looks like the same issue as others have reported: not using a transaction and/or not delegating to the right thread.

IMO it's Panache Reactive which should not allow this usage and throw a better exception.

**Comment by DavideD** [comment]
> This looks like the same issue as others have reported: not using a transaction and/or not delegating to the right thread.

I think so, but I prefer to check with the test case

**Comment by Sanne** [comment]
(I don't know for sure and will let @DavideD reprodice and confirm, I'm just suspecting this might be the case since I see RestEasy being used in the stacktrace)

**Comment by hernael** [comment]
https://github.com/hernael/reactive-demo

**Comment by hernael** [comment]
in repository example is even worse, since it gives error in all requests :(

**Comment by hernael** [comment]
please note that just created a service called hello/first. It does not have initial concurrency. Now, if  service "hello/first" is executed at first and then execute "hello" service, then no error is present

**Comment by DavideD** [comment]
Yes, this is the problem  @Sanne was talking about.
When I run the test I have the following exception:
```
021-02-01 17:25:34,176 ERROR [org.jbo.res.res.i18n] (executor-thread-5) RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.jboss.resteasy.spi.ApplicationException: java.lang.AssertionError: This needs to be run on the Vert.x event loop
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:183)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.AssertionError: This needs to be run on the Vert.x event loop
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.<init>(ReactiveSessionImpl.java:129)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.openSession(MutinySessionFactoryImpl.java:67)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer.createMutinySession(ReactiveSessionProducer.java:32)
```

**Comment by hernael** [comment]
You say that the problem is resteasy? even if concurrent panache reactive code work fine with just before execute a call to non-concurrent panache code?
Note: an unit test only to repository layer also fails

**Comment by DavideD** [comment]
This will work if you wrap everything in a transaction:
```
   public Uni<PageResponse<Entity>> getPage() {
        return Panache.withTransaction(() -> {
            var query = this.findAll();
            var list = query.page( Page.of( 1, 10 ) ).list();
            var total = query.count();
            return Uni.combine().all().unis(list, total).asTuple().onItem().transform((tuple) ->
                PageResponse.<Entity>newBuilder()
                    .setElements(tuple.getItem1())
                    .setTotalCount(tuple.getItem2())
                    .build() );
        });
    }
```

**Comment by hernael** [comment]
Ok, i will use this way.
But i still think there are an issue in somewhere. Maybe in future releases no longer have to use transaction in this case.
In any case, thank you very much!!!

**Comment by Sanne** [comment]
> You say that the problem is resteasy? even if concurrent panache reactive code work fine with just before execute a call to non-concurrent panache code?

Well it's not RESTEasy's fault, but a limitation of our current integration: it's expected to run all Hibernate Reactive code within a reactive context - which at this time means within the same Vert.x eventloop as the vert.x SQL client which it's using underneath.

Failing to run it on the right thread will produce such obscure errors; we certainly need to fix this.

N.B. if you run you reproducer as a test it will fail, as there are assertions which explicitly check for this code to be run on the right thread. One way we could fix this is to promote such assertions to hard requirements - haven't done so yet as we were exploring options, and trying to figure if there was a way to allow this without being that restrictive.

**Comment by hernael** [comment]
Now, after calling a simple request to panache reactive, all subsequent concurrent request to database work fine!
I do not know how initialization connections works in panache reactive, but from the behavior and the error "Session/EntityManager is closed" all this looks like initialization connections trouble in hibernete reactive.
Isn't it?

but anyway, thanks for helping me and giving me a solution to my issue

**Comment by Sanne** [comment]
> I do not know how initialization connections works in panache reactive, but from the behavior and the error "Session/EntityManager is closed" all this looks like initialization connections trouble in hibernete reactive.
Isn't it?

The code is fine but a single Session is not designed to be threadsafe; a consequence of running this on the wrong thread is that both your original thread and the Vert.x thread make state changes, leading likely to illegal state (and complex to diagnose issues).

So we need to ensure all operations are being scheduled on the right thread.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by hernael** [comment]
this still fails for me in version 1.11.3

**Comment by FroMage** [comment]
So, I'm a bit puzzled by the state of this issue. What is wrong and what can we fix?

It looks like we're getting cryptic exceptions such as `java.lang.IllegalStateException: session is currently connecting to database` which is a totally bogus error message which does not _at all_ reflect what's going on.

I was sorta believing that the issue was that we were invoking an operation on a worker thread which is forbidden, but I tried it in resteasy-reactive and got the same issue on an IO thread.

So let's ask this very clearly @Sanne @DavideD @gavinking:

- what operations can I do on the reactive session without a transaction?
- is there a different outcome depending on which thread is calling the operation? As in: should be it a worker thread or an IO thread?
- who is going to fix the error message? I could fix it in the Panache layer when I access a reactive session: I can check the current thread, not sure if I can check if there's a current transaction, though (how?). But, won't this affect even users of the reactive session without the Panache layer? If yes, then that error check belongs in the HR quarkus extension, or the HR session itself, no?

**Comment by DavideD** [comment]
> what operations can I do on the reactive session without a transaction?

I don't think in this  case the problem is the lack of a transaction, I think the issue get solved because when one calls `withTransaction` the block of code runs in the right Vert.x context. As far as I know one could do some reads without a transaction. What happens when we call `Panache.withTransaction`?

> is there a different outcome depending on which thread is calling the operation? As in: should be it a worker thread or an IO thread?

In Hibernate Reactive we check two things:
* The thread must be an eventLoopThread using ` io.vertx.core.ContextContext.isOnEventLoopThread()`
* The thread that has created the session is the same thread that is now doing the operation

I don't know if this answer your question.

> who is going to fix the error message? I could fix it in the Panache layer when I access a reactive session: I can check the current thread, not sure if I can check if there's a current transaction, though (how?). But, won't this affect even users of the reactive session without the Panache layer? If yes, then that error check belongs in the HR quarkus extension, or the HR session itself, no?

We probably need to have better error messages on the Hibernate Reactive side. But first we need to understand a bit better why this is happening

I didn't have much time to investigate this issue further, but I should be able to get back to it soon

**Comment by Sanne** [comment]
@FroMage please see `org.hibernate.reactive.common.InternalStateAssertions` : it expects a system property to be set to enable the assertions that Davide is mentioning.

I had hopes to enable these assertions by default, but I wasn't able to do so as it would break Panache apparently. That's precisely the issue I asked you about some months ago, but then you had been drafted to work on other things...  I hope you could make Panache work now with the checks enabled?

As you can see it can be quite confusing when those assertions don't hold.

**Comment by Sanne** [comment]
BTW the system property is set for the integration tests using Hibernate Reactive which don't use Panache; see:
 - integration-tests/hibernate-reactive-postgresql/pom.xml
 - integration-tests/hibernate-reactive-db2/pom.xml
 - integration-tests/hibernate-reactive-mysql/pom.xml
 -

**Comment by FroMage** [comment]
Well, it's not just setting up the assertion checks, right? If we want to make this work transparently for Panache, we need to start switching to the right thread behind the scenes if required, right?

**Comment by Sanne** [comment]
@FroMage right, I need you to patch Panache Reactive to run things on the right thread. Enabling the assertions should help you to verify being on the right track - and when you're done I'll patch Hibernate Reactive to enable the assertions by default.

What we need is all Quarkus integration tests (including those using Panache) to be able to pass with those assertions enabled.

cc/ @DavideD @gavinking

**Comment by geoand** [comment]
I was talking to @FroMage about some other stuff and he suggested this was a problem that we would need to solve before doing anything else, so I volunteered to have a look to provide a fresh pair of eyes.

_Disclaimer: I don't know much about HR, so my conclusions might be entirely mistaken._

First of all, I used the reproducer, but switched to RESTEasy Reactive in order to ensure that no threading issues exist during the request handling.
Using that, I was consistently able to reproduce:

```
2021-05-11 13:23:21,961 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-35) Request failed: java.lang.IllegalStateException: session is currently connecting to database
```

when hitting http://localhost:8080/hello. This was the case for both the supplied version of Quarkus and Quarkus from `main`.

Following a debugging session, I believe that the problem is simply that the operations performed by the application (`Repository#getPage`) are happening concurrently (due to the use of `Uni.combine()`) which leads to the fact that the first operation has not finished obtaining and setting the connection when the second operation requests a connection - this leads to the error we see (which AFAICT, is not bogus).

The reason the problem goes away when the operations of `Repository#getPage` are wrapped in `Panache.withTransaction` is because by the time the actual operations try to obtain that connection, the connection has already been set by virtue of the transaction being started (which of course entails that the connection was obtained)

**Comment by geoand** [comment]
Have the latest fixes in Hibernate Reactive Panache addressed this issue?

**Comment by Sanne** [comment]
@geoand good point, sorry I forgot to check this issue. I'll do that now.

**Comment by geoand** [comment]
Thanks!

**Comment by gavinking** [comment]
> Following a debugging session, I believe that the problem is simply that the operations performed by the application ...  are happening concurrently (due to the use of `Uni.combine()`) which leads to the fact that the first operation has not finished obtaining and setting the connection when the second operation requests a connection - this leads to the error we see (which AFAICT, is not bogus).

Wait, then why is this issue even still open?

*Of course* it's wrong to have a single session shared between concurrent threads, and always has been, in any flavor or Hibernate!

Can we just close this now.

**Comment by Sanne** [comment]
@gavinking the user isn't controlling the Session use explicitly, this is done via the Panache magic. So yes you're right of course that  this is illegal from the Hibernate perspective, but we should fix the fact that this could happen behind the user's back - remember this is an old issue so it's most likely fixed with the Panache Reactive fixes we just discussed last week.

**Comment by Sanne** [comment]
This seems indeed working fine now. Thanks all!

**Comment by gavinking** [comment]
@Sanne OK 👍

**Comment by hernael** [comment]
hi @Sanne,
I currently upgraded to version 2.1.1 and the issue persists.

```
Caused by: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
	at org.hibernate.reactive.pool.impl.ProxyConnection.withConnection(ProxyConnection.java:66)
	at org.hibernate.reactive.pool.impl.ProxyConnection.selectJdbc(ProxyConnection.java:124)
	at org.hibernate.reactive.loader.ReactiveLoader.executeReactiveQueryStatement(ReactiveLoader.java:129)
	at org.hibernate.reactive.loader.ReactiveLoader.doReactiveQueryAndInitializeNonLazyCollections(ReactiveLoader.java:69)
	... 38 more
```

**Comment by Sanne** [comment]
@hernael interesting, but with the same reproducer? I had tested this again, wondering if I made a mistake.

**Comment by Sanne** [comment]
I've had another look and yes it's failing still - but it depends on the effective order of execution of the tasks being passed onto `Uni.combine().all().unis(list, total)`, so I guess this explains why I might have seen it pass.

Having had a better look now, I suspect the failure is now triggered by different reasons than before: those multiple operations are being scheduled w/o a running Transaction.  You can see that if you annotate the `getPage()` method with `@ReactiveTransactional` it all works correctly.

But I'll leave this open for now: at very least we need to provide a better error message, and I'm wondering if we should make Transactions mandatory or if that's going too far.

It certainly seems necessary to ensure the connection is initialized before using a `combine()`.

**Comment by Sanne** [comment]
@FroMage this seems to highlight a problem with the `executeInVertxEventLoop` delegation we crafted in `io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations<PanacheQueryType>`.

The following code works correctly:

```
public Uni<PageResponse<Entity>> getPage() {
        PanacheQuery<Entity> query = this.findAll();
        Uni<List<Entity>> list = query.page(Page.of(1, 10)).list();
        return list.chain( results -> this.findAll().count().map( count -> PageResponse.<Entity>newBuilder()
                .setElements(results)
                .setTotalCount(count)
                .build()) );
    }
```

But this one might - at random - work fine, or get in a deadlock, or timeout:
```
public Uni<PageResponse<Entity>> getPage() {
        PanacheQuery<Entity> query = this.findAll();
        Uni<List<Entity>> list = query.page(Page.of(1, 10)).list();
        Uni<Long> total = query.count();
        return list.chain( results -> total.count().map( count -> PageResponse.<Entity>newBuilder()
                .setElements(results)
                .setTotalCount(count)
                .build()) );
    }
```

Can you spot the difference? What can we do to either detect the problem, or prevent it?

(ignoring that `@ReactiveTransactional` also prevents any issue)

**Comment by geoand** [comment]
Is this still a problem with the latest Quarkus?

**Comment by mkouba** [comment]
It's still a "problem". I can confirm that Sanne's [solution](https://github.com/quarkusio/quarkus/issues/14709#issuecomment-894243543) works perfectly but it's not very obvious for beginners (like me ;-) and the error message is completely useless.

**Comment by hernael** [comment]
> Is this still a problem with the latest Quarkus?

Hi @geoand, yes this is still a problem.
Although if we add @ReactiveTransactional annotation to the method then it already works correctly.
However I think that this "trick" should not be done, since there are two "SELECT" queries and there is no transaction.

**Comment by geoand** [comment]
Thanks for the info folks

**Comment by FroMage** [comment]
Pfff, to get back to @Sanne's issue, which is:

Without a transaction, if we obtain two `Uni` executing an operation, and execute them without chaining them, something gets broken in HR.

I mean, correct me if I'm wrong, but this seems to be a problem entirely unrelated with Quarkus or Panache.

In any case, to get back to the drawing board, I recall that Julien Viet and @cescoffier told me that with things like Netty's async operations, even if you don't chain the returned promises, they should still all be executed in the sequence that you obtained/invoked them in. Because Netty keeps a queue underneath, so invocation order is always preserved.

Now, this is true in the context of eager promises. But `Uni` are lazy, and only execute on subscription, which means it's the subscription order that should order the operations. OTOH, I'm pretty sure that HR uses `CompletionStage` underneath, which are eager, so I'm not sure about the order semantics of HR calls.

This really looks like a more fundamental question than this issue illustrates.

**Comment by Sanne** [comment]
> Pfff, to get back to @Sanne's issue, which is:
> 
> Without a transaction, if we obtain two `Uni` executing an operation, and execute them without chaining them, something gets broken in HR.

This is most likely relating with the ordering of events. When using the Transaction to wrap all operations, the beginning of the transaction enforces opening of a connection and at that point HR will enforce that such connection-opening work and all subsequent operations are executed within the same vertx. context.

> 
> I mean, correct me if I'm wrong, but this seems to be a problem entirely unrelated with Quarkus or Panache.

It relates to Quarkus as it should ensure different tasks are not re-ordered or dispatched to multiple vertx. context, multiple verticles, other threads, etc...

> In any case, to get back to the drawing board, I recall that Julien Viet and @cescoffier told me that with things like Netty's async operations, even if you don't chain the returned promises, they should still all be executed in the sequence that you obtained/invoked them in. Because Netty keeps a queue underneath, so invocation order is always preserved.

Sure. But Quarkus doesn't seem to honour the premise: there are multiple parallel threads executing multiple vertx contexts. Need to ensure all end user tasks are dispatched consistently and respecting the expected order.

> 
> Now, this is true in the context of eager promises. But `Uni` are lazy, and only execute on subscription, which means it's the subscription order that should order the operations. OTOH, I'm pretty sure that HR uses `CompletionStage` underneath, which are eager, so I'm not sure about the order semantics of HR calls.

It's been a long time since I made the above "spot the difference" comment so TBH I don't remember it all, but I *think* the gist was that one of the code examples triggers use of `executeInVertxEventLoop` in such a way to throw off the sequential ordering guarantees one would expect.

**Comment by DavideD** [comment]
It's also not possible to use `CompletableFuture.allOf(  )` or `Uni.combine().all()` with Hibernate Reactive. That's because the order of the operations using the same session is not guaranteed. Maybe it works in this case but it's something one should not rely on.

That's why the first solution proposed by @Sanne works.
I would also expect the second example to work. I need to check what's going on with it.

We briefly explain this in the [Hibernate Reactive guide](http://hibernate.org/reactive/documentation/1.1/reference/html_single/#_sessions_and_vert_x_contexts).

Like @FroMage said, Hibernate Reactive internally uses the `CompletionStage` API, but the `Mutiny` layer on top of it should create a "lazy layer" that it's only executed at subscription time.

**Comment by hernael** [comment]
Please remember that if you first execute another simple method to establishes connection and then call the complex method with `Uni.combine().all()` (doesn't matter @ReactiveTransactional annotation) everything works OK

**Comment by clahres** [comment]
@DavideD do I understand you correctly that I should not use a pattern like this when using hibernate reactive? Even if the `@ReactiveTransactional` annotation "fixes" the issue?
```kotlin
  @GET
  @ReactiveTransactional
  fun range(
      @QueryParam("startDate") startDate: LocalDate,
      @QueryParam("endDate") endDate: LocalDate
  ): Uni<List<Entry>> {
    return Multi.createFrom()
        .items(startDate.datesUntil(endDate.plusDays(1)))
        .onItem()
        .transformToUniAndMerge { entryResource.list(userRef = "puschel", date = it) }
        .collect()
        .asList()
        .onItem()
        .transform { it.flatten() }
  }
````
`entryResource.list` looks like:
```kotlin
  @GET
  fun list(
      @QueryParam("userRef") @DefaultValue("") userRef: String,
      @QueryParam("page") @DefaultValue("0") pageIndex: Int = 0,
      @QueryParam("size") @DefaultValue("100") pageSize: Int = 100,
      @QueryParam("date") date: LocalDate?
  ): Uni<List<Entry>> {
    val query = if (date == null) "userRef = :userRef" else "userRef = :userRef and date = :date"
    val params = mutableMapOf<String, Any>("userRef" to userRef)
    date?.let { params.put("date", it) }
    return repository.find(query, params).page<Entry>(Page.of(pageIndex, pageSize)).list()
  }
````

**Comment by einarjohnson** [comment]
I am facing the same problem where I encounter the `session is currently connecting to database` error when combining uni's that have performed a read-only operation on the database. what is the best practise here to avoid this error?

**Comment by DavideD** [comment]
@clahres That's correct, you shouldn't run code like that, the problem is that you are using `transformToUniAndMerge` and  sharing the session. Basically, you are running queries in parallel using the same session. This might work in some situations but it's not something one should rely on. I think `transformToUniAndConcatenate` is the correct one to use (but I need to doublecheck that it actually runs the queries one after the other).

@einarjohnson I would have to look at the code, but it usually happens that there a session used in parallel somewhere.

**Comment by einarjohnson** [comment]
@DavideD I have a test that reproduces this error.

```java
@QuarkusTest
public class TestPanache {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(TestPanache.class);

    @Inject
    @Named("MySqlShipmentRepository")
    ShipmentRepository shipmentRepository;

    @Test
    public void testPanacheMutinyFind_SessionError(){
        List<Integer> ids = List.of(123,571,298109,1239,29,1,666,1337);
        UniJoin.Builder<Shipment> builder = Uni.join().builder();
        for(Integer id: ids){
            builder.add(shipmentRepository.findById(1));
        }
        List<Shipment> shipments = builder.joinAll().andCollectFailures().await().atMost(Duration.ofSeconds(30L));
        log.info("Results", shipments);
    }
}
```
Should I use some other "pattern" when calling the Panache repository method multiple times?

**Comment by DavideD** [comment]
It doesn't seem correct.

I don't think `joinAll` guarantees the order of the operations, so, even if in this simple scenario it might work, it's not something that one should rely on. That's because all the operations in that loop use the same session when running the `findById`.

This means that  running two or more findById, could potentially change the state of the session concurrently. I don't mean concurrently as in "different thread", I mean concurrently as it's happening in two different parallel execution streams.

Probably, the transaction gives some guarantees about when the session gets opened and closed. That's why you don't see the error any more.

**Comment by einarjohnson** [comment]
In short, we are writing a lambda handlers that are processing a batch of messages either from Kafka or SQS. The idea is to iterate over all the elements in the batch and call the database similar to how this test is doing it. In the end we have to await on these uni's since we are running inside an AWS lambda.  @DavideD, what is the "best practise" here? Should we not use `joinAll` to do this and some other operator instead?

**Comment by DavideD** [comment]
You need to run a query only after the previous one has completed:
```
    @ReactiveTransactional
    public Uni<List<Shipment>> callDatabase() {
        List<Integer> ids = List.of(123,571,298109,1239,29,1,666,1337);
        List<Shipment> shipments = new ArrayList<>();
        Uni<Void> loop = Uni.createFrom().voidItem();
        for(Integer id: ids){
            loop = loop.call( () -> shipmentRepository
                            .findById(id)
                            .invoke(shipments::add));
        }
        return loop.replaceWith(shipments) ;
    }
```

**Comment by einarjohnson** [comment]
@DavideD , thank you very much for your feedback/help here, I will try this out. <3

**Comment by crionuke** [comment]
Hey, everyone. I have the same issue yet.

How I can achieve concurrency (without "session is currently connecting to database") in a case when I have a Multi with items to handle and if sequential execution database requests is not an option for me?

My example (I've tried to add ".emitOn(Infrastructure.getDefaultWorkerPool())" and Panache.withTransaction() for every batch of changes, but it doesn't work as expected)
```
    @Scheduled(every = "1s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
    Uni<Void> dispatch() {
        return Multi.createFrom().iterable(topics)
                .onItem().transformToUniAndMerge(this::handleTopic)
                .collect().last().replaceWithVoid();
    }

    Uni<Void> handleTopic(final String topic) {
        log.info("Handle topic, topic={}", topic);
        return topicsJavaClient.getCachedTopic(topic)
                .onItem().transformToMulti(cachedTopic -> Multi.createFrom().iterable(cachedTopic
                        .getCachedSubscribers()))
                .emitOn(Infrastructure.getDefaultWorkerPool())
                .onItem().transformToUniAndMerge(this::handleSubscriberDeliveries)
                .collect().last().replaceWithVoid();
    }

    Uni<Void> handleSubscriberDeliveries(CachedSubscriber cachedSubscriber) {
        log.info("Handle subscriber's deliveries, topic={}, group={} uri={}",
                cachedSubscriber.getTopic(), cachedSubscriber.getGroupUuid(), cachedSubscriber.getUri());
        return Panache.withTransaction(() -> handleSubscriberDeliveriesOperation
                .handleSubscriberDeliveries(cachedSubscriber)
                .replaceWithVoid());
    }
```

**Comment by crionuke** [comment]
Hello, everyone! I have the same issue.
So, how to achieve concurrency within the "reactive" method in working with DB? 

There is my example:
```
Uni<Void> dispatch() {
    List<Uni<Void>> handlers = Arrays.asList(
            createHandler(1),
            createHandler(2),
            createHandler(3));
    return Uni.join().all(handlers).andCollectFailures()
            .replaceWithVoid();
}

Uni<Void> createHandler(int index) {
    return Uni.createFrom().item(index)
            .emitOn(Infrastructure.getDefaultWorkerPool())
            .invoke(i -> handle(i))
            .replaceWithVoid();
}

void handle(int index) {
    log.info("handle, {}", index);
    Panache.withTransaction(() -> eventRepository.deleteAll()) // just for instance
            .await().indefinitely();
}
```

Extra questions:
- Is available to control when a reactive session will be created?
- Why is there an error with the wrong thread names? (my threads are "executor-thread-*", but in the logs "vert.x-eventloop-thread-2")

Logs

```
2023-02-03T15:31:37.738+04:00 [] (**executor-thread-1**) INFO  [co.om.pu.se.fe.sc.DispatcherScheduledTask.handle:64] handle, 2
2023-02-03T15:31:37.738+04:00 [] (**executor-thread-0**) INFO  [co.om.pu.se.fe.sc.DispatcherScheduledTask.handle:64] handle, 1
2023-02-03T15:31:37.738+04:00 [] (**executor-thread-2**) INFO  [co.om.pu.se.fe.sc.DispatcherScheduledTask.handle:64] handle, 3
2023-02-03T15:31:37.983+04:00 [] (main) ERROR [io.qu.ar.im.AbstractInstanceHandle.destroyInternal:89] Error occurred while destroying instance of bean [io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [163]: '**vert.x-eventloop-thread-5**' current Thread [158]: '**vert.x-eventloop-thread-2**'

```

**Comment by DavideD** [comment]
I will need to check but I think the use of the emit on on the worker thread, causes the creation of multiple event loop thread. That's because the Hibernate Reactive only works on an event loop thread. The problem is that `Panache.withTransaction` won't create a new session each time, and therefore you have multiple threads using the same session. 

If you want to execute tasks concurrently (in the sense of parallel reactive streams) you need to create a new session each time. I think you can only do this with the Hibernate Reactive session factory. Something like this should work:

```java
       @Inject
       Mutiny.SessionFactory sf;

       Uni<Void> dispatch() {
               return Uni.join()
                    .all(Arrays.asList( createHandler(1), createHandler(2) ,createHandler(3) )
                    .andCollectFailures()
                    .replaceWithVoid();
       }

	Uni<Void> createHandler(int index) {
		log.info("handle, {}", index);
		return getMutinySessionFactory()
				.openSession()
				.chain( session -> session
						.withTransaction( tx -> deleteAll( session, tx ) )
						.eventually( session::close )
				);
	}

	private Uni<Void> deleteAll(Mutiny.Session session, Mutiny.Transaction tx) {
		try {
			return session.createQuery( "..." ).executeUpdate().replaceWithVoid();
		}
		catch (Throwable t) {
			// We need to make sure that any exception get caught so that it's
			// always possible to close the session in case of error
			return Uni.createFrom().failure( t );
		}
	}
```    

There is [an issue with .eventually(...) not actually handle all possible scenario](https://github.com/smallrye/smallrye-mutiny/issues/1181), but it should be fixed in the next Mutiny release.

**Comment by crionuke** [comment]
@DavideD 
Yea, thanks. I've also tried to use the withTransaction method from Mutiny.SessionFactory to acquire an auto-closable session object. And it works. But is sad because I can't use panache to work with DB in that case.

**Comment by einarjohnson** [comment]
@DavideD, I have tried the code you suggested and it the `session is currently connecting to database` error has now disappeared, so thank you very much for the help on that issue. :)

However, I am now seeing a very strange issue crop up now and then when this code runs. It looks as if the `shipmentRepository.findById(id)` method sometimes returns "stale" or "cached" data that is not reflecting the actual values that are stored in the MySQL database. 

I can easily reproduce this locally by putting a breakpoint on the `findById` method at the `onItem` line. 

```
public Uni<com.controlant.sls.core.domain.models.Shipment> findById(long shipmentId) {
    return find("shipment_id", shipmentId).firstResult()
            .call(shipment -> Mutiny.fetch(shipment.loggers))
            .onItem().transform(shipmentResponse -> shipmentResponse.toDomainShipment());
}
```

When I go to the MySQL database directly and update the shipments table and set some columns to a new value and then re-run `findById` method I notice that after a couple of iterations of doing so the update statements I performed have no effect and I keep getting the same values returned in the `shipmentResponse`  object even though the table itself has a new value set in it's columns.

Do you know what might be causing this? It feels like some kinda caching issue and I have tried setting the `quarkus.hibernate-orm.second-level-caching-enabled` to `false` without any luck.

**Comment by DavideD** [comment]
You have already figured it out.
There is only one session, the first time you load the value it gets cached in the session and it will stay there until you destroy the session or clear it.

Keep in mind that a [session](https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_obtaining_a_reactive_session) is a lightweight object that should represent a logical single unit of work.

I'll admit that in Quarkus, at the moment, it's hard to figure out when a session is created or destroyed. We are working on it.

**Comment by einarjohnson** [comment]
Great, it's good to know I am at least on the right track with this. :)
I think it would be super beneficial to add this to the https://quarkus.io/guides/hibernate-reactive documentation as it isn't very clear you need to do this "magic" when querying the DB using the repository pattern. 

@DavideD , do you know when your work might be released into the Quarkus framework? I would like to stay up-to-date and have the codebase as simple as possible if you guys are planning to make changes to the Hibernate/Panache API.

**Comment by DavideD** [comment]
The best way to keep track of the changes is to follow the labels [area/panache](https://github.com/quarkusio/quarkus/labels/area%2Fpanache) or [area/hibernate-reactive](https://github.com/quarkusio/quarkus/labels/area%2Fhibernate-reactive).

A PR with a big set of changes has already been sent: https://github.com/quarkusio/quarkus/pull/29761
But it shouldn't cause too many changes to your code.

**Comment by DavideD** [comment]
I've just realized that if `withTransaction` throws an exception, the session might not get closed.
Probably better to change the code to:
```java
Uni<Void> createHandler(int index) {
		log.info("handle, {}", index);
		return getMutinySessionFactory()
				.openSession()
				.chain( session -> deleteAll( session, tx ).eventually( session::close ) );
	}

private Uni<Void> deleteAll(Mutiny.Session session, Mutiny.Transaction tx) {
		try {
			return session.withTransaction( tx -> session.createQuery( "..." ).executeUpdate() ).replaceWithVoid();
		}
		catch (Throwable t) {
			// We need to make sure that any exception get caught so that it's
			// always possible to close the session in case of error
			return Uni.createFrom().failure( t );
		}
	}
```

**Comment by geoand** [comment]
Do we know if this problem still exists in the latest issues of Quarkuys?

**Comment by DavideD** [comment]
As far as I understand the original problem was about using `.combine().all()`. Something the Hibernate Reactive doesn't support.  I guess we can close this issue

**Comment by geoand** [comment]
Thanks @DavideD
