### ISSUE TITLE
NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#19139]
### Describe the bug

Since 2.1 I get
`NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image`

### Expected behavior

A working application

### Actual behavior

Error on startup

### How to Reproduce?

Starting the project

### Output of `uname -a` or `ver`

Linux martind-linuxiator 5.13.6-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 29 Jul 2021 00:21:08 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment (build 16.0.2+7) OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.1.0.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.2 (Oracle Corporation 16.0.2+7)
OS:           Linux 5.13.6-zen1-1-zen amd64
```

### Additional information

[quarkus-error-reproducer.tar.gz](https://github.com/quarkusio/quarkus/files/6909327/quarkus-error-reproducer.tar.gz)

**Comment by MartinX3** [comment]
Replacing
`implementation("io.quarkus.platform:quarkus-bom:$quarkusVersion")`
by
`implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:2.1.0.Final"))`
fixed the issue.
It seems I misread the migration wiki and the blog.

**Comment by jmini** [comment]
In our case the root module does not contains any sources. It is only containing other modules and defining some common build behavior in the `subprojects` section.

The root module is not a java project. The hint given in the previous comment https://github.com/quarkusio/quarkus/issues/19139#issuecomment-950121475 does not work (the `dependencies` block is not even expected).

For some (legacy?/unknown) reason I have noticed that we were using `platform(..)` and not `enforcedPlatform(..)`. This seems to help solving the `SRCFG00011` issue.

My changes:

```diff
diff --git a/<sub-project>/build.gradle b/<sub-project>/build.gradle
index 1ac60b5..2b7ac18 100644
--- a/<sub-project>/build.gradle
+++ b/<sub-project>/build.gradle
@@ -1,6 +1,6 @@
 dependencies {
     // quarkus:
-    implementation platform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
+    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
     implementation 'io.quarkus:quarkus-smallrye-health'
     implementation ...
     implementation ...
```

Also some of our modules are using the `api` configuration instead of the `implementation` configuration (also not sure about the reason). So I am changing the enforced platform on that scope as well (but I am not sure if this is really needed):

```diff
diff --git a/<other-sub-project>/build.gradle b/<other-sub-project>/build.gradle
index eec174a..691569b 100644
--- a/<other-sub-project>/build.gradle
+++ b/<other-sub-project>/build.gradle
@@ -1,5 +1,5 @@
 dependencies {
-    implementation platform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
+    api enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
     implementation 'io.quarkus:quarkus-kotlin'
     implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
     implementation 'io.quarkus:quarkus-arc'
     // some quarkus dependencies are on the 'api' configuration
```

**Comment by gechregofix** [comment]
In our case we are working with a multi module project with a root gradle and different child gradles. Adding the following snipped

```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
}
```

outside of the subprojects lead into other exceptions where the gradle subprojects could not find defined dependencies. I made it work by having the above code part outside of subprojects aswell as inside. In the root gradle.

**Comment by jmini** [comment]
My changes discussed in https://github.com/quarkusio/quarkus/issues/19139#issuecomment-2519449460 helped, but it didn't solve the problem every-time.

I am now switching to version [`3.17.8`](https://github.com/quarkusio/quarkus/releases/tag/3.17.8), because it seems that something similar has been fixed: https://github.com/quarkusio/quarkus/issues/45472

**Comment by gsmet** [comment]
@jmini yeah, it looks like the same issue. Let us know how it goes for you. If we're lucky, we might be able to close this one too :).
