### ISSUE TITLE
Response has already been written Exception

### ISSUE THREAD

**Issue by MM87037** [quarkusio/quarkus#19835]
### Describe the bug

When using lazy JWT authentication with http permissions observing below exception if JWT token in the request is expired. Also this exception is thrown only if a FailureRoute is defined.

2021-09-01 15:00:05,611 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router: java.lang.IllegalStateException: Response has already been written

Quarkus Extensions used: cdi, security, smallrye-context-propagation, smallrye-jwt, smallrye-openapi, swagger-ui, vertx, vertx-web

Config used:

```
quarkus.http.auth.proactive=false
quarkus.http.auth.permission.permit.paths=/q/*,/api/hello
quarkus.http.auth.permission.permit.policy=permit
quarkus.http.auth.permission.loggedin.paths=/api/*
quarkus.http.auth.permission.loggedin.policy=authenticated
```

### Expected behavior

No Runtime exceptions

### Actual behavior

Observed below exception

```
2021-09-01 15:00:05,611 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router: java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.Http1xServerResponse.checkValid(Http1xServerResponse.java:669)
	at io.vertx.core.http.impl.Http1xServerResponse.endHandler(Http1xServerResponse.java:310)
	at io.vertx.ext.web.impl.RoutingContextImpl.getEndHandlers(RoutingContextImpl.java:573)
	at io.vertx.ext.web.impl.RoutingContextImpl.addEndHandler(RoutingContextImpl.java:436)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:90)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:22)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1133)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:148)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:591)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:184)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:173)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$3.accept(HttpAuthorizer.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$3.accept(HttpAuthorizer.java:137)
```

### How to Reproduce?

https://github.com/MM87037/routing-error

Start the service and run below command
```
curl "http://localhost:8080/api/user" -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJUZXN0Iiwic3ViIjoidW5tVW93TlBRNVEzdVh4WDNPRVkwTnRTRnNOWFZ6SlZnYVZyNm40MWNYbyIsInByZWZlcnJlZF91c2VybmFtZSI6IlRlc3RVc2VyQGNvbXBhbnkuY29tIiwiYXVkIjoiZjkzZWUxYTgtYmExYS00NDk0LWJmZTEtNjQzODIzMDIyNWVhIiwiaWF0IjoxNjI5NzMzMzE1LCJleHAiOjE2Mjk3MzY5MTUsIm5hbWUiOiJUZXN0IFVzZXIiLCJyb2xlcyI6WyJ3cml0ZSIsInJlYWQiLCJyZWxlYXNlIl0sImp0aSI6ImUzMGMxNWZjLTA0YzEtNDM0Yi1iZTZjLTU0N2E3Zjk4MjI0MiJ9.f52Q1JrH4JjeDbwn4NthuBYursCjeRrgd4uvCx0wGpilxaOVm7nvHlFkTKbiRofpEl8kE4YEangEGpiXPfn33Q5fZ_C2TjgQyrbNu9-IbSeDStLxIbhawW-NjyTI3EQY0zUrN9aOHvOWDitNTUVjBxHCIf1WTmyL15X6XT1qBczpTZKr-kkFs2L0Gxereu_gNxWgUPcyfC0vTOhjt3prZcpksv2W26gpKdTdJBmXm0xeOlkdxeIao_2kiJWTxJ22aUSLCESodNex-QV-40EjUz7B4YHSfEJ16mUjgLAOcpIwjjjZAvdHV92oa6alIgbbb35VjeqlPmKc29gQJNQP1Q'
```
or

Run maven build
```
mvn clean verify
```

### Output of `uname -a` or `ver`

Linux service-117-qd7hx 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### Quarkus version or git rev

2.0 and above

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.1

**Comment by MM87037** [comment]
I have raised a simillar issue (https://github.com/quarkusio/quarkus/issues/19621) last week which got fixed in 2.2.1.Final

**Comment by sberyozkin** [comment]
@MM87037 Is it the same issue as #19621 ? It was already fixed by Stuart

**Comment by MM87037** [comment]
@sberyozkin No its not the same issue. I did highlight this issue as well previously but only "Response head already sent Exception" is fixed. 

I have run the test again with 2.2.1.Final today and I can still see "Response has already been written" error. Note this error is thrown only when a Failure route handler is defined in the app.
