### ISSUE TITLE
Logs for Quarkus jvm mode app in Docker have java.util.logging format

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2145]
Logs for Quarkus jvm mode app in Docker have java.util.logging format

JVM mode:
```
docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm
exec java -Dquarkus.http.host=0.0.0.0 -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.2:8778/jolokia/
Apr 18, 2019 10:11:24 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.0.Final
Apr 18, 2019 10:11:24 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.0.Final
Apr 18, 2019 10:11:24 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Alpha4
Apr 18, 2019 10:11:24 AM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 999-SNAPSHOT started in 1.469s. Listening on: http://0.0.0.0:8080
Apr 18, 2019 10:11:24 AM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [cdi, resteasy]
```

Native mode:
```
docker run -i --rm -p 8080:8080 quarkus/getting-started
2019-04-18 09:29:59,127 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.003s. Listening on: http://0.0.0.0:8080
2019-04-18 09:29:59,128 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by gsmet** [comment]
This is with a fresh install? Because I fixed something related to that very recently?

See https://github.com/quarkusio/quarkus/commit/d0cb45ade657ee7b3d0221cef31ef6bfc1fa08c5 .

The log output is OK if not running with Docker (e.g. doing `java -jar` directly?)

**Comment by rsvoboda** [comment]
It's fresh master from today. Java way not running in Docker is fine, see below.
I think it's related to fabric8/java-jboss-openjdk8-jdk image we use.

```
java -jar target/getting-started-1.0-SNAPSHOT-runner.jar
2019-04-18 14:16:35,411 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.019s. Listening on: http://[::]:8080
2019-04-18 14:16:35,420 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by dmlloyd** [comment]
The underlying issue is #2152, but let's see if we can find which component is starting logging too early.

**Comment by gsmet** [comment]
It might be related to the agent this image is including.

@johnaohara we really need to fix this image issue I think and get away from the one we use currently. Did you make progress on this front?

**Comment by dmlloyd** [comment]
Yup agents commonly initialize logging too early.  The workaround is to make it pass `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` to the JVM.

**Comment by gsmet** [comment]
Maybe we could include that in the Docker file but we really need to fix this image issue anyway as apparently performances with the current one are pretty bad.

**Comment by gsmet** [comment]
@rsvoboda @johnaohara changed the image. Can you check if it resolves the issue?

**Comment by rhuss** [comment]
for the notes: The reason in this case it not that the agent themselves use the logger too early, but its the used JDK dependencies that use jul logging during initialization. In the case of Jolokia this was the com.sun.net.httpserver who does this. I can't really comment on jmx_exporter though.

This is solved for JBoss / Wildfly by doing a lazy init. Jolokia has a server detection for this, but doesn't know yet about Quarkus.

If you can tell me a system property or any other unique indication (like a class loaded) how to detect whether running in a quarkus app, I can add such an handler to Jolokia easily to do that kind of lazy init to.

If you use a recent fabric8 base image, you can set the proper JAVA_OPTIONS for setting the log manager, too

**Comment by rhuss** [comment]
> @rsvoboda @johnaohara changed the image. Can you check if it resolves the issue?

could you please point me to the Dockerfile or where the image is changed ?

**Comment by johnaohara** [comment]
@rhuss I am testing now to see if we still see the issue, and will test adding JVM options suggested by @dmlloyd

**Comment by johnaohara** [comment]
@rhuss the docker template is here: https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/resources/templates/dockerfile-jvm.ftl

**Comment by rhuss** [comment]
thanks !

Some remarks:

* You can use the environment variable`AB_ENABLED=jmx_exporter` to switch on only Prometheus `jmx_exporter` and turn off Jolokia. See https://github.com/fabric8io-images/java/tree/master/images/alpine/openjdk8/jre for all options.
* You shouldn't be required to provide the ENTRYPOINT. The entry point is inherited from the base image
* Have you considered to use fabric8io/docker-maven-plugin ? With this you can use exactly this Dockerfile, use the plugin without **any** configuration, and build and push images with `mvn docker:build` and `mvn docker:push` (with various authentication methods, including GCR and ECR authentication) without the need of a Docker CLI locally installed. Also, you can bind them to the appropriate execution phases, for an even smoother image build experience. Note, that docker-maven-plugin is an independent project (independent from fabric8-maven-plugin) and actively maintained. It's focus is on image building (and container runs for integration testing), and does not do any k8s manifest generation. In the future there will be support for Jib and other daemonless builds. tl;dr - If your Dockerfie is located in your top-level dir, all you would need todo is to add 

```xml
<plugin>
   <groupId>io.fabric8</groupId>
   <artifactId>docker-maven-plugin</artifactId>
   <version>0.29.0</version>
</plugin>
```

**Comment by rsvoboda** [comment]
I still see java.util.logging format with "fabric8/java-alpine-openjdk8-jre" based image

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"

cd getting-started/
mvn package
docker build -f src/main/docker/Dockerfile.jvm -t quarkus/getting-started-jvm-x .
docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm-x
```
```
exec java -Dquarkus.http.host=0.0.0.0 -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.2:8778/jolokia/
Apr 23, 2019 11:13:09 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Alpha4
Apr 23, 2019 11:13:09 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.0.Final
Apr 23, 2019 11:13:09 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.0.Final
Apr 23, 2019 11:13:09 AM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 999-SNAPSHOT started in 1.586s. Listening on: http://0.0.0.0:8080
Apr 23, 2019 11:13:09 AM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [cdi, resteasy]
```

**Comment by rsvoboda** [comment]
When I change src/main/docker/Dockerfile.jvm
```
ENV JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
```
to 
```
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
```
I no longer see java.util.logging format from Quarkus
```
docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm-x && docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm-x
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.2:8778/jolokia/
2019-04-23 11:15:46,242 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.495s. Listening on: http://0.0.0.0:8080
2019-04-23 11:15:46,290 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by dmlloyd** [comment]
As long as there's an agent that initializes logging, it will use the JDK logger, until #2152 is resolved.

**Comment by gsmet** [comment]
@rsvoboda we need to check carefully Roland's comment here: https://github.com/quarkusio/quarkus/issues/2145#issuecomment-484847662

I think we should add `AB_ENABLED=jmx_exporter`.

**Comment by rsvoboda** [comment]
As https://github.com/quarkusio/quarkus/pull/2181 is merged I think we can close this one.

The underlying issue is tracked in #2152.
