### ISSUE TITLE
JWT Authorization skipped for POST with body

### ISSUE THREAD

**Issue by Eldelshell** [quarkusio/quarkus#21571]
### Describe the bug

The JWT authorization is skipped on an endpoint with a body.

```
    @POST
    @Path("/secured/bugged")
    @RolesAllowed({"User"})
    public Response helloSecured(MyRequest req) {
        System.out.println("You shouldn't be here");
        System.out.println(req);
        return Response.ok("{\"message\":\"you shouldn't be here\"}").build();
    }
    
    private static class MyRequest {
        public String name;
    }
```

```
$ curl -X POST -H "Content-Type: application/json" -i http://localhost:8080/hello/secured/bugged
HTTP/1.1 200 OK
Content-Type: application/json
content-length: 35
```

Without a body, it works correctly:

```
    @POST
    @Path("/secured/works")
    @RolesAllowed({"User"})
    public Response helloSecured() {
        return Response.ok().build();
    }
```

```
$ curl -X POST -i http://localhost:8080/hello/secured/works
HTTP/1.1 401 Unauthorized
www-authenticate: Bearer
content-length: 0

```

### Expected behavior

It should return a 401 and doesn't allows access to the method

### Actual behavior

It returns a 200 and continues into the endpoint method

### How to Reproduce?

```
$ git clone git@github.com:Eldelshell/jwt-bug.git
$ cd jwt-bug
$ mvn clean install
$ mvn quarkus:dev
```
...in another terminal...
```
$ curl -X POST -H "Content-Type: application/json" -i http://localhost:8080/hello/secured/bugged
```

### Output of `uname -a` or `ver`

x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

When calling an endpoint without a body argument the logs show:

```
2021-11-19 14:13:14,990 DEBUG [io.sma.jwt.auth] (vert.x-eventloop-thread-12) SRJWT06000: tokenHeaderName = Authorization
2021-11-19 14:13:14,990 DEBUG [io.sma.jwt.auth] (vert.x-eventloop-thread-12) SRJWT06005: Authorization header was null
2021-11-19 14:13:15,011 DEBUG [io.qua.res.runtime] (executor-thread-0) Create constructor: public io.quarkus.resteasy.runtime.SecurityContextFilter()
2021-11-19 14:13:15,013 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002315: PathInfo: /hello/secured/works
```

When calling the conflicting endpoint:

```
2021-11-19 14:13:53,516 DEBUG [io.sma.jwt.auth] (vert.x-eventloop-thread-0) SRJWT06000: tokenHeaderName = Authorization
2021-11-19 14:13:53,518 DEBUG [io.sma.jwt.auth] (vert.x-eventloop-thread-0) SRJWT06005: Authorization header was null
2021-11-19 14:13:53,522 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002315: PathInfo: /hello/secured/bugged
2021-11-19 14:13:53,525 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) Interceptor Context: org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext,  Method : proceed
2021-11-19 14:13:53,528 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) MessageBodyReader: org.jboss.resteasy.core.providerfactory.SortedKey
2021-11-19 14:13:53,528 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) MessageBodyReader: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2021-11-19 14:13:53,529 DEBUG [org.jbo.res.res.i18n] (executor-thread-0) Provider : org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider,  Method : readFrom
You shouldn't be here
```

**Comment by Eldelshell** [comment]
Adding an invalid JWT works:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer foo" -i http://localhost:8080/hello/secured/bugged
HTTP/1.1 401 Unauthorized
www-authenticate: Bearer
content-length: 0
```

**Comment by sberyozkin** [comment]
Hmm, very strange, I wonder, can it be the case that a body processor loses the security identity...

**Comment by sberyozkin** [comment]
@Eldelshell Not sure why it fails for you, I've added these tests:

#21579

**Comment by sberyozkin** [comment]
@Eldelshell

**Comment by Eldelshell** [comment]
Did what you suggested and still not getting a 401

**Comment by Eldelshell** [comment]
For the new one it works:
```
$ curl -X POST -H "Content-Type: application/json" -i http://localhost:8080/hello/secured/bugged-text
HTTP/1.1 401 Unauthorized
www-authenticate: Bearer
content-length: 0
```

It seems the issue only affect when the argument is an object... maybe the deserialization phase is skipping the JWT security context?

**Comment by sberyozkin** [comment]
@Eldelshell I saw 401, I think, but I've tried with the snapshot:
https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#using-snapshots

Can you please try them ?

```
-    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
-    <quarkus.platform.version>2.4.2.Final</quarkus.platform.version>
+    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
+    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>

```

I've updated my PR with JSON tests and they also work with jsonb (the current dependency for those tests) but I also tried Jackson and it was fine.

Looks like some fix has gone into the `main` branch

**Comment by Eldelshell** [comment]
@sberyozkin same:

```2021-11-19 19:45:23,660 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 1.722s. Listening on: http://localhost:8080

2021-11-19 19:45:23,661 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-11-19 19:45:23,662 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, reactive-routes, resteasy, resteasy-jackson, security, smallrye-context-propagation, smallrye-jwt, vertx]
You shouldn't be here
null
```

**Comment by Eldelshell** [comment]
BTW, this issue was detected during testing.

We test that all our endpoints are secured and well, this one wasn't passing a simple test:

```
@QuarkusTest
@TestHTTPEndpoint(MessageResource.class)
@TestInstance(Lifecycle.PER_CLASS)
public class MessageResourceTest {

    @Test
    public void test_changeName_Insecure() {
        given()
            .contentType(ContentType.JSON)
            .when()
            .post(UUID.randomUUID().toString() + "/changeName")
            .then()
            .statusCode(Status.UNAUTHORIZED.getStatusCode());
    }
```

**Comment by sberyozkin** [comment]
@Eldelshell I'm sorry - it also fails for me - though works as expected for a `bugged-text` request as I said above. 
Hmm, I'd like to see what others observe - as you can see the PR works

**Comment by sberyozkin** [comment]
No idea what is going on...PR is also failing but with some weird error

**Comment by Eldelshell** [comment]
I've tried with PUT and PATCH and same behavior:

```
    @PATCH
    @Path("/secured/bugged")
    @RolesAllowed({"User"})
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON_PATCH_JSON)
    public Response helloSecuredPatch(@Valid MyRequest req) {
        System.out.println("PATCH You shouldn't be here");
        System.out.println(req);
        return Response.ok("{\"message\":\"you shouldn't be here\"}").build();
    }
    
    @PUT
    @Path("/secured/bugged")
    @RolesAllowed({"User"})
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public Response helloSecuredPut(@Valid MyRequest req) {
        System.out.println("PUT You shouldn't be here");
        System.out.println(req);
        return Response.ok("{\"message\":\"you shouldn't be here\"}").build();
    }
```

```
POST You shouldn't be here
null
PUT You shouldn't be here
null
PATCH You shouldn't be here
null
```

```
$ curl -X PATCH -H "Content-Type: application/json-patch+json" -i http://localhost:8080/hello/secured/bugged
HTTP/1.1 200 OK
Content-Type: application/json
content-length: 35

{"message":"you shouldn't be here"}

$ curl -X PUT -H "Content-Type: application/json" -i http://localhost:8080/hello/secured/bugged
HTTP/1.1 200 OK
Content-Type: application/json
content-length: 35

{"message":"you shouldn't be here"}
```

**Comment by Eldelshell** [comment]
@sberyozkin seeing the tests, there's none for no JWT, like:

```
    @Test
    public void postJsonNoToken() {
        RestAssured.given()
                .header("Content-Type", "application/json")
                 //.auth().oauth2("invalid")
                .when()
                .body("{\"name\":\"alice\"}")
                .post("/endp/postInjectedPrincipalJson")
                .then().statusCode(401);
    }
```

**Comment by sberyozkin** [comment]
@Eldelshell I don't think it matters which verb is used, something strange is going on, I've just fixed my PR and it will be green and as you can see a valid token with a missing role is rejected with 403, invalid token - with 401, with the post and the JSON body.
Lets wait for more feedback from others

Thanks

**Comment by sberyozkin** [comment]
@Eldelshell 

> seeing the tests, there's none for no JWT

have just pushed it as well

**Comment by Eldelshell** [comment]
Today I ran the tests on #21579 and everything works. Maybe this tests aren't loading the whole servlet context and only the security ones? When I ran a similar test with `@QuarkusTest` I get the same behavior described here.

**Comment by sberyozkin** [comment]
@stuartwdouglas Can you please have a quick look at #21579 and the code at git@github.com:Eldelshell/jwt-bug.git, may be you can spot something that may affect the tests failing at git@github.com:Eldelshell/jwt-bug.git ? 

My own local tests showed that the tests at git@github.com:Eldelshell/jwt-bug.git accept a plain string as opposed to JSON, hence #21529 tries both String and JSON payloads - in the latter case it is a JSONB provider is used but I also checked locally with Jackson and they also worked...

**Comment by Eldelshell** [comment]
Hi, I added the tests to verify that the bug still occurs when using `@QuarkusTest`

https://github.com/Eldelshell/jwt-bug/blob/6deada4c4db7a5ccaec8f33d6cb6d9686e9decf4/src/test/java/org/acme/GreetingResourceTest.java#L16

and yes, they problem is still present:

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   GreetingResourceTest.testBug_PATCH:42 1 expectation failed.
Expected status code <401> but was <200>.

[ERROR]   GreetingResourceTest.testBug_POST:22 1 expectation failed.
Expected status code <401> but was <200>.

[ERROR]   GreetingResourceTest.testBug_PUT:32 1 expectation failed.
Expected status code <401> but was <200>.

```

**Comment by sberyozkin** [comment]
@Eldelshell @stuartwdouglas I've pushed more tests, involving `@QuarkusTest`, both `@TestSecurity` and a complete end to end (with JSON and text) tested.
Not sure what is going on

**Comment by Eldelshell** [comment]
I added more tests to the greeting project and the results are:

- Without a body on the request: 200 (should be 401)
- With a valid body: 200 (should be 401)
- With an invalid body: 200 (should be 401)
- With an invalid content type header: 415 (not sure if it should be 401 so it might work as expected)

I also tried to inject the JsonWebToken and got the same results.

**Comment by sberyozkin** [comment]
Hmm, at the moment I've no idea what is different between your setup and the integration test setup, I've tried the 2.5. and 2.x branches with my PR and the tests pass...

**Comment by sberyozkin** [comment]
@Eldelshell OK, found it, `MyRequest` is `private static` and it must be public - I think we have a duplicate somewhere.

**Comment by sberyozkin** [comment]
@Eldelshell Closing as a duplicate of #19177 - thanks for spending the time on it - we'll either update Quarkus to fail the build in such cases or at least doc a warning, please watch #19177 and comment there as well

**Comment by Eldelshell** [comment]
Just tested this and you're correct, changing to public made it work. Thanks!

**Comment by sberyozkin** [comment]
@Eldelshell Thanks for confirming, in meantime we'll try to do something about preventing hard to diagnose sec problems when the private entities are used :-)
