### ISSUE TITLE
Reactive REST client: Request body not serialized to JSON for custom content type (`application/custom+json`)

### ISSUE THREAD

**Issue by softmetz** [quarkusio/quarkus#25652]
### Describe the bug

When the reactive REST client is supposed to send a request body (e.g. POST) and get the annotation `@Consumes("application/custom+json")` the body object is just strinigified.

With `@Consumes("application/json")` it works just as expected.

### Expected behavior

The request body object should be serialized to JSON.

### Actual behavior

toString() gets called on the request body object.

### How to Reproduce?

1. Create reactive REST client that takes a POJO as request body parameter  and annotate with `@Consumes("application/custom+json")`
2. Extract the outgoing traffic to see that the `content-type` header is set properly but the body itself is just the `toString()` value

### Output of `uname -a` or `ver`

Linux nb0mws009 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment (build 17.0.3+7-Debian-1deb11u1) OpenJDK 64-Bit Server VM (build 17.0.3+7-Debian-1deb11u1, mixed mode, sharing)

### Quarkus version or git rev

2.9.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

That might be related to #21957 but for the sending side.

**Comment by michalszynkiewicz** [comment]
isn't it a duplicate of https://github.com/quarkusio/quarkus/issues/15982 ?

**Comment by Sgitario** [comment]
I think this issue should be fixed after https://github.com/quarkusio/quarkus/pull/25739 is merged. @softmetz can you double check that this issue is resolved with these changes? Or provide a reproducer, so we can check ourselves.

**Comment by softmetz** [comment]
I have created https://github.com/softmetz/quarkusio-25652-json-custom-type 
There are two test cases, one for `application/json` and one for `application/custom+json`.

The latter one will fail by:

```
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/hello                                                     | /hello
                                                           |
content-type: application/custom+json                      | content-type: application/custom+json
                                                           |
{                                                          | com.acme.SomePojo@29118c4b                          <<<<< Body does not match
  "some" : "foo",                                          |
  "pojo" : "bar"                                           |
}                                                          |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

I hope that helps to see the problem more easily.

Please notice, that I am using 2.9.1 so the bug is still there.

**Comment by Sgitario** [comment]
> I have created https://github.com/softmetz/quarkusio-25652-json-custom-type There are two test cases, one for `application/json` and one for `application/custom+json`.
> 
> The latter one will fail by:
> 
> ```
>                                                Request was not matched
>                                                =======================
> 
> -----------------------------------------------------------------------------------------------------------------------
> | Closest stub                                             | Request                                                  |
> -----------------------------------------------------------------------------------------------------------------------
>                                                            |
> POST                                                       | POST
> /hello                                                     | /hello
>                                                            |
> content-type: application/custom+json                      | content-type: application/custom+json
>                                                            |
> {                                                          | com.acme.SomePojo@29118c4b                          <<<<< Body does not match
>   "some" : "foo",                                          |
>   "pojo" : "bar"                                           |
> }                                                          |
>                                                            |
> -----------------------------------------------------------------------------------------------------------------------
> ```
> 
> I hope that helps to see the problem more easily.
> 
> Please notice, that I am using 2.9.1 so the bug is still there. And it applies to `PUT` either.

Thanks for the reproducer. 
I could confirm that https://github.com/quarkusio/quarkus/pull/25739 fixed this issue as well. 
Closing as it was duplicated by https://github.com/quarkusio/quarkus/issues/15982.
