### ISSUE TITLE
ClassNotFoundException when using quarkus:dev

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#2809]
Hello @quarkus Team :)

I have a ~~multimodule~~ [project](https://github.com/sarxos/abberwoult) with ~~one of modules being~~ an example subproject which exposes very simple REST API. Everything works fine when I start this example with a runner:

```plain
java -jar target/abberwoult-example-0.0.1-SNAPSHOT-runner.jar -cp target/lib/*
```

The resource is started and I can access REST API. This is ok but takes some time, so I wanted to use `mvn quarkus:dev`. ~~I see that support for `quarkus:dev` in multimodule projects was introduced by https://github.com/quarkusio/quarkus/pull/1973 and thus should be working fine,~~ But when I try to run my example with a dev mojo, that is:

```plain
$ cd abberwoult-example
$ mvn quarkus:dev
```

I'm getting the following error:

```plain
18:12:22,936 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:129)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:173)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:100)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	... 8 more
Caused by: java.lang.IllegalStateException: Cannot load com.example.FruitRepositoryActor
	at com.github.sarxos.abberwoult.deployment.ActorInterceptorRegistryTemplate.register(ActorInterceptorRegistryTemplate.java:25)
	at io.quarkus.deployment.steps.AbberwoultProcessor$doRegisterActors9.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.AbberwoultProcessor$doRegisterActors9.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.example.FruitRepositoryActor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.sarxos.abberwoult.deployment.ActorInterceptorRegistryTemplate.register(ActorInterceptorRegistryTemplate.java:23)
	... 11 more
```

This error comes from a `@Template` annotated class which is pretty simple:

```java
@Template
public class ActorInterceptorRegistryTemplate {

	private static final Logger LOG = LoggerFactory.getLogger(ActorInterceptorRegistry.class);

	public void register(final String className) {

		final Class<?> clazz;
		try {
			clazz = Class.forName(className);
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException("Cannot load " + className, e);
		}

		LOG.debug("Loaded {}", clazz);

		ActorInterceptorRegistry.registerReceiversFrom(clazz);
		ActorInterceptorRegistry.registerPreStartsFrom(clazz);
		ActorInterceptorRegistry.registerPostStopsFrom(clazz);
	}
}
```

I was able to w/a this by implementing custom class loader which loads classes directly from a known location, but some other issue (class not found exception, again) appeared which is probably linked to the same problem but is thrown from a synthetic beans so I gave up in digging more.

This is my custom class loader I implemented to (partially) workaround described problem:

```java
public static class CustomClassLoader extends ClassLoader {

	@Override
	public Class<?> findClass(String name) throws ClassNotFoundException {
		final byte[] b = loadClassFromFile(name);
		return defineClass(name, b, 0, b.length);
	}

	private byte[] loadClassFromFile(final String className) throws ClassNotFoundException {

		LOG.debug("Loading class {}", className);

		final String resourcePath = className.replace('.', File.separatorChar) + ".class";

		int value = 0;

		try (
			final InputStream is = new FileInputStream(resourcePath);
			final ByteArrayOutputStream baos = new ByteArrayOutputStream()) {

			while ((value = is.read()) != -1) {
				baos.write(value);
			}

			return baos.toByteArray();

		} catch (FileNotFoundException e) {
			throw new ClassNotFoundException("Cannot find resource " + resourcePath, e);
		} catch (IOException e) {
			throw new IllegalStateException(e);
		}
	}
}
```

To reproduce:

```plain
$ git clone git@github.com:sarxos/abberwoult.git
$ cd abberwoult
$ mvn clean install -DskipTests
$ cd abberwoult-example
$ mvn quarkus:dev
```

**Comment by sarxos** [comment]
UPDATE: 

After excluding example from a Maven modules and converting it to separate project the issue is still there. This proves that this is not multimodule-related. I'm updating the title and description accordingly.

**Comment by gsmet** [comment]
@stuartwdouglas could you take a look at this one?

**Comment by stuartwdouglas** [comment]
Does it work when running with -DnoDeps? I tried to build the project locally but was missing com.github.sarxos:oss-parent:pom:6-SNAPSHOT

**Comment by stuartwdouglas** [comment]
There are some known issues around having both extensions and projects using those extensions in the same project. The multimodule support will assume the extensions should be part of the app, and load them into the wrong class loader. If this is the underlying problem then noDeps should fix it.

**Comment by sarxos** [comment]
Hi @stuartwdouglas,

Unfortunately. Option `-DnoDeps` did not fix it.

Just to make things easier I created a very minimal example and uploaded it into a new project https://github.com/sarxos/quarkus-issue-2809. The names of directories and modules are exactly the same as in my original project (I was too lazy to change them all) but all of my code is removed and only very basic reproducer classes are added instead.

These reproducer classes are:

The class from `abberwoult` module (this module is a runtime part of Quarkus extension):

```java
package com.github.sarxos.abberwoult;

public class TestClassDependency {
}
```

The class from `abberwoult-example` module:

```java
package com.example;

public class TestClassProject {
}
```

A `@Template` class which also belongs to `abberwoult` module:

```java
package com.github.sarxos.abberwoult;

import io.quarkus.runtime.annotations.Template;

@Template
public class TestClassTemplate {

	public void test(String clazz) {
		try {
			Class.forName(clazz);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
}
```

And a `@BuildStep` in `abberwoult-deployment` module (this one is a deployment part of Quarkus extension) which records template invocation for these two test classes:

```java
package com.github.sarxos.abberwoult;

import static io.quarkus.deployment.annotations.ExecutionTime.STATIC_INIT;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.annotations.Record;

public class AbberwoultProcessor {

	@BuildStep
	@Record(STATIC_INIT)
	public void doTest(final TestClassTemplate template) {
		template.test("com.github.sarxos.abberwoult.TestClassDependency");
		template.test("com.example.TestClassProject");
	}
}
```

To reproduce:

1. `git clone git@github.com:sarxos/quarkus-issue-2809.git`
2. `cd quarkus-issue-2809`
3. `mvn clean install`
4. `cd abberwoult-example`
5. `mvn quarkus:dev` or `mvn quarkus:dev -DnoDeps` (no difference in output)

Observe:

* Class from dependency **is** loaded,
* Class from a project **is not** loaded.

```plain
java.lang.ClassNotFoundException: com.example.TestClassProject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.sarxos.abberwoult.TestClassTemplate.test(TestClassTemplate.java:11)
	at io.quarkus.deployment.steps.AbberwoultProcessor$doTest2.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.AbberwoultProcessor$doTest2.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:113)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:157)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:84)
```

**Comment by sarxos** [comment]
Hi @stuartwdouglas,

Have you had a chance to take a look at the reproducer I prepared?

https://github.com/sarxos/quarkus-issue-2809

**Comment by Delfic** [comment]
I'm having a similar problem. I'm using a specific class to use on the camel-core component. When I run it works, when I run in dev mode I get a `ClassNotFoundException` at ` at io.quarkus.camel.core.deployment.CamelInitProcessor.visitService(CamelInitProcessor.java:154)`
I'm wondering why that works not on dev mode, is it using `camel-core` instead of `quarkus-camel-core`. How would that make a difference to the classpath?

Additionally, I debugged this and on the classloading step I tried to load other classes from my project and they were not loaded as well. I'm guessing that at that step we don't have the classes of the project available.

I could w/a this but is it intended for the classloading happen at a point where the project classes are not in there?

**Comment by rdehuyss** [comment]
I'm also having trouble with this...

My current workaround is to do this:
public static Class<?> loadClass(String className) throws ClassNotFoundException {
        try {
            return Class.forName(className);
        } catch (ClassNotFoundException e) {
            return currentThread().getContextClassLoader().loadClass(className);
        }
    }

instead of 
`Class.forName(className);`

**Comment by stuartwdouglas** [comment]
Class.forName() without a CL is often problematic. In general you should always use the TCCL.

**Comment by stuartwdouglas** [comment]
I am closing this, as there are no plans to enable Class.forName() to work for every situation (this can only be done with a flat classpath, which means no hot reload). If you use the 3 argument version and pass in the TCCL this should work fine.

**Comment by Mobe91** [comment]
@stuartwdouglas Then you should also adopt the example in https://quarkus.io/guides/writing-extensions#scanning-deployments-using-jandex which uses `Class.forName`.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/11485

**Comment by vamsisayimpu** [comment]
#TODO: Quakrus Testing framework uses QuarkusClassLoader, for workaround use this below property in test/app.properties
quarkus.test.flat-class-path=true
