### ISSUE TITLE
MongoDB Client integration-test fails in native mode 

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#29402]
### Describe the bug

MongoDB Client integration-test, and more specifically `io.quarkus.it.mongodb.NativeBookResourceIT.health`, started failing in the CI of [Mandrel](https://github.com/graalvm/mandrel/actions/runs/3519788151) and [GraalVM](https://github.com/oracle/graal/actions/runs/3520053674)

First observed failing commit: 3c920f76932d66a05f2dbee129a8b2571fb4ebc1 in https://github.com/graalvm/mandrel/actions/runs/3493647357/jobs/5861267577
Last known working commit: ff044fff4a1e46cef4dca011ba07de18cc317451 in https://github.com/graalvm/mandrel/actions/runs/3484788102/jobs/5829991956

### Expected behavior

Test should pass

### Actual behavior

Test fails at runtime with:

```
Error:  io.quarkus.it.mongodb.NativeBookResourceIT.health  Time elapsed: 0.012 s  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class io.quarkus.test.mongodb.MongoTestResource
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:337)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:110)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class io.quarkus.test.mongodb.MongoTestResource
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class io.quarkus.test.mongodb.MongoTestResource
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:477)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: java.lang.IllegalArgumentException: could not resolve package for V4_2:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu}
--------------
(os=Windows)
  (os=Windows and bitSize=B64) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
    url=/windows/mongodb-windows-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
    url=/win32/mongodb-win32-x86_64-2012plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (4.0.0-4.0.27 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
    url=/win32/mongodb-win32-x86_64-2008plus-ssl-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-2008plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/win32/mongodb-win32-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B32) and (3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-i386-{version}.zip (ZIP)
  (os=Windows and bitSize=B32) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/win32/mongodb-win32-i386-{version}.zip (ZIP)
  (os=Windows)
    fail
(os=OS_X)
  (os=OS_X and bitSize=B64) and (4.0.0-4.0.27 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.4-3.0.15)
    url=/osx/mongodb-osx-ssl-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (3.5.5-3.5.5 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.3.1-3.3.1 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/osx/mongodb-osx-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
    url=/osx/mongodb-macos-x86_64-{version}.tgz (TGZ)
  (os=OS_X)
    fail
(os=Linux)
  (os=Linux and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10))
    (os=Linux and bitSize=B64 and (version is any of Ubuntu_20_04, Ubuntu_20_10)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
      url=/linux/mongodb-linux-aarch64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of Ubuntu_20_04, Ubuntu_20_10)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
      url=/linux/mongodb-linux-x86_64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
      url=/linux/mongodb-linux-aarch64-ubuntu1804-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.1-4.0.27 or 3.6.20-3.6.23)
      url=/linux/mongodb-linux-x86_64-ubuntu1804-{version}.tgz (TGZ)
  (os=Linux and (version is any of LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3, LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3))
    use Ubuntu_18_04 for LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3 and Ubuntu_20_04 for LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3
  (os=Linux and (version is any of DEBIAN_10, DEBIAN_9))
    (os=Linux and bitSize=B64 and (version is any of DEBIAN_9)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.27 or 3.6.5-3.6.23)
      url=/linux/mongodb-linux-x86_64-debian92-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of DEBIAN_10)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.1-4.2.3)
      url=/linux/mongodb-linux-x86_64-debian10-{version}.tgz (TGZ)
  (os=Linux and (version is any of CentOS_6, CentOS_7, CentOS_8, Redhat_6, Redhat_7, Redhat_8, Oracle_6, Oracle_7, Oracle_8))
    (os=Linux and bitSize=B64 and (version is any of CentOS_6, Redhat_6, Oracle_6)) and (4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.27 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel62-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of CentOS_7, Redhat_7, Oracle_7)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.27 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel70-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of CentOS_8, Redhat_8, Oracle_8)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.1-4.2.3 or 4.0.14-4.0.27 or 3.6.17-3.6.23 or 3.4.24-3.4.24)
      url=/linux/mongodb-linux-x86_64-rhel80-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of CentOS_8, Redhat_8, Oracle_8)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.4-4.4.9)
      url=/linux/mongodb-linux-aarch64-rhel82-{version}.tgz (TGZ)
  (os=Linux and (version is any of AmazonLinux, AmazonLinux2))
    (os=Linux and bitSize=B64 and (version is any of AmazonLinux2)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.4-4.4.9 or 4.2.18-4.2.18 or 4.2.13-4.2.16)
      url=/linux/mongodb-linux-aarch64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of AmazonLinux2)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.27 or 3.6.22-3.6.23)
      url=/linux/mongodb-linux-x86_64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and (version is any of AmazonLinux)) and (5.0.5-5.0.5 or 5.0.0-5.0.2 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.18 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.27 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-amazon-{version}.tgz (TGZ)
  (os=Linux and bitSize=B64) and (4.0.0-4.0.26 or 3.6.0-3.6.22 or 3.4.9-3.4.23 or 3.4.0-3.4.7 or 3.2.0-3.2.21 or 3.0.0-3.0.14 or 2.6.0-2.6.12)
    url=/linux/mongodb-linux-x86_64-{version}.tgz (TGZ)
  (os=Linux and bitSize=B32) and (3.2.0-3.2.21 or 3.0.0-3.0.14 or 2.6.0-2.6.12)
    url=/linux/mongodb-linux-i686-{version}.tgz (TGZ)
  (os=Linux and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/linux/mongodb-linux-x86_64-{version}.tgz (TGZ)
  (os=Linux and bitSize=B32) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/linux/mongodb-linux-i686-{version}.tgz (TGZ)
  (os=Linux)
    fallback to Ubuntu_20_04
(os=Solaris)
  (os=Solaris and bitSize=B64) and (3.4.0-3.4.5 or 3.2.0-3.2.14 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/sunos5/mongodb-sunos5-x86_64-{version}.tgz (TGZ)
  (os=Solaris and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/sunos5/mongodb-sunos5-x86_64-{version}.tgz (TGZ)
  (os=Solaris)
    fail

	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.lambda$packageFor$0(PlatformPackageResolver.java:66)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:60)
	at de.flapdoodle.embed.process.store.ArtifactStore.filesToExtract(ArtifactStore.java:93)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:84)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	at io.quarkus.test.mongodb.MongoTestResource.doGetExecutable(MongoTestResource.java:108)
	at io.quarkus.test.mongodb.MongoTestResource.getMongodExecutable(MongoTestResource.java:96)
	at io.quarkus.test.mongodb.MongoTestResource.start(MongoTestResource.java:71)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:471)
	... 4 more
```

### How to Reproduce?

1. `git clone git@github.com:quarkusio/quarkus.git`
2. `cd quarkus`
3. `./mvnw -Dquickly -T2`
4. 
```
./mvnw -e --settings .github/mvn-settings.xml --fail-at-end \
    -f integration-tests -pl mongodb-client \
    -Dtest-containers -Dstart-containers \
    -Dquarkus.native.native-image-xmx=5g -Dnative \
    -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests \
    clean install -DskipDocs \
    -Dquarkus.native.container-build=true
```

### Output of `java -version`

openjdk 17.0.6-beta 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+3-202211172333 (build 17.0.6-beta+3-202211172333) OpenJDK 64-Bit Server VM Temurin-17.0.6+3-202211172333 (build 17.0.6-beta+3-202211172333, mixed mode, sharing)

### GraalVM version (if different from Java)

22.3.0

### Quarkus version or git rev

3c920f76932d66a05f2dbee129a8b2571fb4ebc1

### Additional information

I was able to reproduce the issue:

1. Locally with GraalVM CE 22.3.0 locally installed
2. Locally with the Mandrel 22.3.0 builder image
3. On github actions with both GraalVM and Mandrel builds of `master`
4. On [github actions with the Mandrel 22.3.0 builder image and Quarkus 2.14.1](https://github.com/graalvm/mandrel/actions/runs/3501607739/jobs/5865538437#step:11:399)
5. On [github actions with the Mandrel 22.3.0 builder image and Quarkus 2.13 branch](https://github.com/graalvm/mandrel/actions/runs/3501607739/jobs/5865553411#step:11:392)

**Comment by zakkak** [comment]
Hmm I was also able to reproduce with the last known working Quarkus revision (https://github.com/quarkusio/quarkus/commit/ff044fff4a1e46cef4dca011ba07de18cc317451) locally, so it looks like it is something not triggered by a Quarkus or GraalVM/Mandrel change...

**Comment by Karm** [comment]
It has been excluded as not working test in native for some time IMHO:

https://github.com/graalvm/mandrel-packaging/blob/master/jenkins/jobs/tests/Constants.groovy#L38

**Comment by zakkak** [comment]
Interesting, note however that this is not the case for Quarkus GHA, see https://github.com/quarkusio/quarkus/blob/main/.github/native-tests.json#L30.

**Comment by jerboaa** [comment]
> What's even more interesting is that it appears to be passing in the Quarkus `master` runs... see https://github.com/quarkusio/quarkus/actions/runs/3523161137/jobs/5909184730#step:12:318

GHA runner OS difference? I see `Ubuntu 20.04` for the passing one and `Ubuntu 22.04` for the failing one.

**Comment by jerboaa** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/commit/e236b5bf0c402fe6e04ed863cf195cfce6bfbe98 should fix it? Not sure where that dep is declared though.

**Comment by jerboaa** [comment]
Thanks!

**Comment by jerboaa** [comment]
It references `1.0.12` so hopefully fixes this. https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/de.flapdoodle.embed.mongo-3.5.2/pom.xml#L499

**Comment by zakkak** [comment]
> GHA runner OS difference? I see Ubuntu 20.04 for the passing one and Ubuntu 22.04 for the failing one.

Well it's been like this for a while now. Furthermore, both the failing run and the passing run on graalvm/mandrel repo are using the Github runner version 2.299.1, so it doesn't look like a change in the runner either :/

FWIW, I tried [the update of flapdoodle to 3.5.2](https://github.com/quarkusio/quarkus/pull/29414) and I still get the failure on CentOS 9 Stream, which appears to not be present in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/de.flapdoodle.embed.mongo.packageresolver-1.0.12/src/test/java/de/flapdoodle/embed/mongo/packageresolver/linux/CentosRedhatPackageResolverTest.java. We probably need to create an issue for this as well.

In the meantime I have also scheduled a CI run to test https://github.com/quarkusio/quarkus/pull/29414 on the Mandrel CI setup: https://github.com/graalvm/mandrel/actions/runs/3530682797

**Comment by jerboaa** [comment]
> > GHA runner OS difference? I see Ubuntu 20.04 for the passing one and Ubuntu 22.04 for the failing one.
> 
> Well it's been like this for a while now. Furthermore, both the failing run and the passing run on graalvm/mandrel repo are using the Github runner version 2.299.1, so it doesn't look like a change in the runner either :/

I'm seeing this for the [passing one](https://github.com/graalvm/mandrel/actions/runs/3484788102/jobs/5829991956):

```
Current runner version: '2.299.1'
Operating System
  Ubuntu
  20.04.5
  LTS
```

... and this for the [failing one](https://github.com/graalvm/mandrel/actions/runs/3493647357/jobs/5861267577):

```
Current runner version: '2.299.1'
Operating System
  Ubuntu
  22.04.1
  LTS
```

So while the runner image version is the same, the underlying OS is different.

> FWIW, I tried [the update of flapdoodle to 3.5.2](https://github.com/quarkusio/quarkus/pull/29414) and I still get the failure on CentOS 9 Stream, which appears to not be present in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/de.flapdoodle.embed.mongo.packageresolver-1.0.12/src/test/java/de/flapdoodle/embed/mongo/packageresolver/linux/CentosRedhatPackageResolverTest.java. We probably need to create an issue for this as well.

Makes sense. It probably needs support for centos stream/rhel 9. Could you create an issue, please?

**Comment by zakkak** [comment]
Good catch, apparently we are being bitten (or not, since it allowed us to catch the issue) by https://github.com/graalvm/mandrel/blob/bd852ea0608739578fcf7aaa713831f3ca415a96/.github/workflows/base.yml#L88 . I thought I had those fixed to a specific version...

> Makes sense. It probably needs support for centos stream/rhel 9. Could you create an issue, please?

Sure

**Comment by zakkak** [comment]
Closed through #29414 

(Confirmed in https://github.com/graalvm/mandrel/actions/runs/3530682797/jobs/5923305802)
