### ISSUE TITLE
`IllegalAccessError` on `@QuarkusTest` when using method in package private interface

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#29593]
### Describe the bug

`IllegalAccessError` on `@QuarkusTest` when using method in package private interface (through a public interface that extends that one)

### Expected behavior

The test executes.

### Actual behavior

`IllegalAccessError` exception thrown.

### How to Reproduce?

Reproducer: 
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/10126401/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

Darwin N4MFM06QYD 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/xtaixe/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.4, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home Default locale: en_ES, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by manovotn** [comment]
Hm, I am not sure how is this supposed to work.
We need to place the bean proxy in some package - in this case the package of the class which declares the producer method.
And by doing that, such proxy doesn't have access to the `BaseInterface` which is pack-private but at the same time a required bean type which that proxy indirectly implements...

**Comment by manovotn** [comment]
Just tried this with Weld to see if I am missing something obvious but Weld has the exact same issue and it doesn't work there either.

@xtaixe BTW you can make this work by avoiding proxy creation - instead of `@ApplicationScoped`, use `@Singleton`.

**Comment by mkouba** [comment]
This pull request should fix the problem: https://github.com/quarkusio/quarkus/pull/29705

> BTW you can make this work by avoiding proxy creation - instead of `@ApplicationScoped`, use `@Singleton`.

You can also make the `BaseInterface` public or avoid using annonymous classes in the mean time ;-).

**Comment by xtaixe** [comment]
> You can also make the BaseInterface public or avoid using annonymous classes in the mean time ;-).

@mkouba I made it public for now, but in my actual case it is a base interface that shouldn't be exposed. The anonymous class was just for the reproducer, in my actual case it's not and it still happens (just in case you need to review the fix).

**Comment by manovotn** [comment]
> @mkouba I made it public for now, but in my actual case it is a base interface that shouldn't be exposed. The anonymous class was just for the reproducer, in my actual case it's not and it still happens (just in case you need to review the fix).

It depends on the return type of your producer method - if you keep that as an interface, you'll keep seeing the issue.
If you change it to the impl class, it should start working even with the current version.

**Comment by mkouba** [comment]
> in my actual case it's not and it still happens (just in case you need to review the fix).

Hm, does your producer method return an implementation class or an interface? I was not quite clear - I meant the return type of the producer method must not be an interface but an impl class (and no anonymous class needed). The return type is the only source of information when we generate a client proxy for a producer method.

**Comment by xtaixe** [comment]
The return type it's an interface and I don't know the actual type (it's created using a builder). So th issue will keep happening even with the fix?

**Comment by mkouba** [comment]
> The return type it's an interface and I don't know the actual type (it's created using a builder). So the issue will keep happening even with the fix?

Nope, the fix should solve the problem. In this case, the [workaround](https://github.com/quarkusio/quarkus/issues/29593#issuecomment-1339220901) mentioned by @manovotn is the only option.
