### ISSUE TITLE
Kafka MutinyEmitter.sendAndAwait sometimes ruins blocking DB

### ISSUE THREAD

**Issue by mapuci** [quarkusio/quarkus#39098]
### Describe the bug

A very simple reproducer example can be found here:
https://github.com/MatejPucihar/kafka-db-tx
![image](https://github.com/quarkusio/quarkus/assets/20385863/b56f6b05-3955-4c9e-81ba-60569d24ee03)

Scenario: 
- send rest http request (from test, every 1ms, to force exception)
- rest request is handler is a `@Transactional` method, which inserts something in DB and sends something to kafka. It must be blocking send, we want to commit out DB TX only if kafka message is ACKed. 

There is ~1:1000 chance that the handler will fail dramatically:
```
2024-03-01 08:32:55,162 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012094: Commit of action id 0:ffff0a010a48:e441:65e18477:d1d0 invoked while multiple threads active within it.
2024-03-01 08:32:55,163 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012107: CheckedAction::check - atomic action 0:ffff0a010a48:e441:65e18477:d1d0 commiting with 2 threads active!
2024-03-01 08:32:55,163 WARN  [com.arj.ats.jta] (executor-thread-2) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a010a48:e441:65e18477:d1d0, node_name=quarkus, branch_uid=0:ffff0a010a48:e441:65e18477:d1d3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@2ea67dc) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
```

I first saw the exception in quarkus 3.5, when we implemented a feature using it. I decided it is time to solve it now, before we go live :)

I investigated a bit further, placing breakpoints here:
- `/Users/matejpucihar/.m2/repository/org/jboss/narayana/jta/narayana-jta/7.0.0.Final/narayana-jta-7.0.0.Final.jar!/com/arjuna/ats/arjuna/logging/arjunaI18NLogger_$logger.class:693` 
- `com.arjuna.ats.arjuna.coordinator.BasicAction.checkChildren`
![image](https://github.com/quarkusio/quarkus/assets/20385863/c975e3e1-cd2c-406e-b0b5-156c9df0e4fc)
It shows that transaction, that was propagated to kafka-producer-thread is still bound to that thread, after message was ACKED(blocking sendAndAwait). That should not happen?

The exception can be solved using a thread without propagated transaction, e.g. `@ManagedExecutorConfig(cleared = ThreadContext.TRANSACTION)`

I know the concept of `write to kafka, wait for message to be ACKed and then commit DB tx` is weird at best. 
But, still this must be a pretty ugly bug. 

### Expected behavior

Exception should never occur

### Actual behavior

Exception 

### How to Reproduce?

clone https://github.com/MatejPucihar/kafka-db-tx
run `./mvnw test`

### Output of `uname -a` or `ver`

happens on multiple OS/ARCHITECTURES. Linux amd64, Mac M1, K8s cluster... My uname -a outputs Darwin Matejs-MBP-2.medius 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

21.0.2" 2024-01-16

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /Users/matejpucihar/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21.0.2, vendor: Oracle Corporation, runtime: /Users/matejpucihar/Library/Java/JavaVirtualMachines/openjdk-21.0.2/Contents/Home Default locale: sl_SI, platform encoding: UTF-8 OS name: "mac os x", version: "14.2.1", arch: "aarch64", family: "mac"

### Additional information

Error is present for at least a few major quarkus versions.

Error can be bypassed with disabled tx propagation to kafka-producer-thread (e.g. `@ManagedExecutorConfig(cleared = ThreadContext.TRANSACTION)`)

**Comment by ozangunalp** [comment]
We had a similar problem with Kafka serializer touching the managed Hibernate entity during a transaction but this one isn't it. If you remove the flush and only call persist the problem goes away. That way the entity is managed by Hibernate throughout the method calla but only persisted when the transaction is committed not before.

I don't know why flush causes the context propagation to include the Kafka sender thread inside the transaction. Maybe someone with more experience with context propagation can chime in.

**Comment by MatejPucihar** [comment]
We are dealing with legacy DB, using IDENTITY id generator strategy, which causes flush on every new insert/persist :)

**Comment by mmusgrov** [comment]
I don't know what the problem is but I can comment on the symptom: You have started a transaction in one thread which then runs some code in another thread with context propagation enabled. When you commit the transaction, presumably from the first thread, the transaction manager is telling you that the second thread is still active and is running with the transaction associated.
 
If you don't need the second thread to run with the transaction then use your fix by clearing the transaction context, otherwise you could wait for this second thread to return before committing the transaction.

**Comment by mmusgrov** [comment]
I notice that the transaction manager is using "onePhaseCommit" which means there is only one resource involved in the transaction which I assume is the persisting of the JPA entity so it should be fine to clear the transaction context when doing the kafka call.

**Comment by MatejPucihar** [comment]
> I notice that the transaction manager is using "onePhaseCommit" which means there is only one resource involved in the transaction which I assume is the persisting of the JPA entity so it should be fine to clear the transaction context when doing the kafka call.

I 100% agree with everything written. 
I applied the ugly fix, but still, I believe that this bug should be resolved asap. 
I believe that the provided scenario is quite common. Al least in imperative world; write to db, write to kafka, wait ack, commit db tx. 
And having a lib, that has 1:1000 chance of wierd failure is really not great.

While having little/no experience with reactive code and context propagation... I can only guess, what is holding the mutiny-kafka-producer thread bound to thread context after acking the message.

**Comment by cescoffier** [comment]
@ozangunalp, do you know if there were any investigations?

**Comment by ozangunalp** [comment]
I don't think so. 

As I wrote, this is very similar to a case where a serializer touches the entity and Hibernate is not happy with it. 
However, in this case, I believe the "problem" was the fact that flush was called before. 
Another thing to check could be to replace Kafka write with grpc or rest service call. And see if that causes an issue.

**Comment by mapuci** [comment]
I upgraded demo project to quarkus latest 3.15.1. The bug is still present. 

I added a sample method that calls rest client instead of kafka emitter. There is no bug. 
I noticed that transaction is not even propagated when calling rest client. At least it is not present in ClientResponseFilter.

**Comment by ozangunalp** [comment]
The best _workaround_ I found for this issue is to extract the Hibernate persist into its own Transactional method : 
````
    @Transactional
    String persist() {
        final var myEntity = new MyEntity();
        myEntity.field = OffsetDateTime.now().toString();
        myEntity.persist();
        return myEntity.field;
    }
```

By keeping the endpoints non-transactional you no longer have the "Enlisted connection used without active transaction".

**Comment by mapuci** [comment]
You just cannot use an emitter while in transactional block. There are plenty of BAD ways how to achieve that :)

I just cannot understand how am I (or my company) the only one facing this issue all the time... 
The only 'weird' thing we are doing is usage of `idGenerationType = IDENTITY` which causes flush on every persist. 
But AFAIK flush is called before every query, so others should experience the same issue. 

I added another test method which calls this methos (note that `MyEntitySequence` uses SEQUENCE idGenerationStrategy ):
```
    @GET
    @Path("/query-and-send")
    @Produces(MediaType.TEXT_PLAIN)
    public String queryAndSend()
    {
        final var panacheEntityBases = MyEntitySequence.listAll();
        mutinyEmitter.sendAndAwait("hello");
        return "sa";
    }
```
And this also fails :(

**Comment by cescoffier** [comment]
@mapuci your last example does not use transaction, so it's probably something else.

**Comment by FroMage** [comment]
>  the transaction manager is telling you that the second thread is still active and is running with the transaction associated.

Why is it still marked as active, though? `sendAndAwait` should have finished and removed the TX association from the other thread.

> If you don't need the second thread to run with the transaction then use your fix by clearing the transaction context, otherwise you could wait for this second thread to return before committing the transaction.

If it's common for kafka consumers to not need a TX context (or other contexts), perhaps we need to make it easier to obtain a `MutinyEmitter` without context-propagation?

Didn't we talk of adding such facilities, either with an annotation on the emitter, or an API on Mutiny types, @cescoffier @jponge ?

**Comment by mapuci** [comment]
> [@mapuci](https://github.com/mapuci) your last example does not use transaction, so it's probably something else.

@cescoffier class is anotated with @Transactional... 
You can inspect reproducer, link is at issue description.

**Comment by mapuci** [comment]
I will try to describe what happens, step by step:
- TransactionInterceptor starts tx
- jakarta-rest method is invoked, entity is created and persisted
- if entity ID generationStrategy==IDENTITY --> flush is called with persist. (Hibernate must get new ID from DB.)
- if entity ID generationStrategy==SEQUENCE --> flush is NOT called with persist. (Hibernate gets new ID from cache. )
- we call emitter.sendAndAwait(). That is invoked with mutiny(Uni), on eventLoopThread with propagated contexts. And we wait until that eventLoopThread signals complete inside Uni.

- NOW we have 2 threads bound to same TX:
  - executor-thread. That one must do:
    - if entity ID generationStrategy==IDENTITY --> COMMIT
    - if entity ID generationStrategy==SEQUENCE. --> FLUSH + COMMIT
    - NOTE: flush is blocking IO operation... it takes some time.
  - eventLoopThread. That one must do:
    - clean up thread context that was propagated by executor thread.

So, if executorThread wants to commit TX BEFORE eventLoopThread clears its propagated contexts... We have a problem.
Which is ofc more likely to happen when you do not have to call flush.

**Comment by ozangunalp** [comment]
@mapuci I've been looking at this last couple of days. The event loop thread is not involved in the Tx, but the Kafka network thread that is used by the Kafka producer. 

It gets activated because that is the one returning the send confirmation ack, and the context propagation activates the thread for the Tx. 

It has to do with the moment the Tx is committed, this is why in some test cases it is flaky and the id generation strategy has an effect. 

My solution would be to avoid propagating the transaction context to the Emitters. There are several ways to do it:

- You can control the call to emitters in your application code by wrapping the emitter call to clear the transaction context:
```
    @CurrentThreadContext(cleared = ThreadContext.TRANSACTION)
    void sendAndAwait(String payload) {
        mutinyEmitter.sendAndAwait(payload);
    }
```

or 

```
    @CurrentThreadContext(cleared = ThreadContext.TRANSACTION)
    void sendAndForget(String payload) {
        mutinyEmitter.sendAndForget(payload);
    }
```

- You can apply this globally with a Reactive Messaging decorator : 
```
import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;

import org.eclipse.microprofile.context.ThreadContext;
import org.eclipse.microprofile.reactive.messaging.Message;

import io.smallrye.mutiny.Multi;
import io.smallrye.reactive.messaging.PublisherDecorator;

@ApplicationScoped
public class TxContextDecorator implements PublisherDecorator {

    private final ThreadContext tc;

    public TxContextDecorator() {
        tc = ThreadContext.builder().cleared(ThreadContext.TRANSACTION).build();
    }

    @Override
    public Multi<? extends Message<?>> decorate(Multi<? extends Message<?>> toBeSubscribed, List<String> channelName, boolean isConnector) {
        return toBeSubscribed.emitOn(tc.currentContextExecutor());
    }
}
```

We can add checks to apply this to only emitters etc. but this should do the trick.

This should probably be a default in Quarkus, as I don't see any cases where we need to propagate DB Tx context through emitters.


As a note, I also tried to avoid propagating the Tx only in the Kafka connector with no success.

**Comment by mapuci** [comment]
Thanks a lot @ozangunalp !

- indeed it is kafka-network-thread, not the event-loop. it's screenshot is actually in the issue description :)![Image](https://github.com/user-attachments/assets/2201c9d4-5990-4206-8e24-848e8fa265cc)
- I like the idea of `TxContextDecorator`. I will incude it in all my projects ASAP.

I think we need one of the following:
- disable TX propagation to reactive-messaging by default
- include @ozangunalp 's tips'n'tricks into https://quarkus.io/guides/kafka

**Comment by FroMage** [comment]
> I don't see any cases where we need to propagate DB Tx context through emitters.

Well that's a very good question. What contexts need to be propagated through emitters? What do people typically do in receivers? If they are supposed to annotate their receivers with things like `@Transactional` or `@ActivateRequestContext` then the expectation is that zero contexts are supposed to be propagated. But it depends on what people typically do in request contexts.

**Comment by ozangunalp** [comment]
This is resolved by #46174
