### ISSUE TITLE
[JDK 23+14] Running quarkus with latest early access build fails setting the context class loader

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#39526]
### Describe the bug

Running a quarkus-quickstart, e.g. `rest-client-quickstart` with JDK 23+14 fails with:

```
2024-03-18 15:23:03,455 WARN  [io.qua.res.mut.dep.ResteasyMutinyProcessor] (build-6) The quarkus-resteasy-mutiny extension is deprecated. Switch to RESTEasy Reactive instead.
This extension adds support for Uni and Multi to RESTEasy Classic, without using the reactive execution model, as RESTEasy Classic does not use it. To properly integrate Mutiny and RESTEasy, use RESTEasy Reactive. See https://quarkus.io/guides/getting-started-reactive for detailed instructions
Exception in thread "ForkJoinPool.commonPool-worker-6" Exception in thread "ForkJoinPool.commonPool-worker-5" Exception in thread "ForkJoinPool.commonPool-worker-1" Exception in thread "ForkJoinPool.commonPool-worker-8" Exception in thread "ForkJoinPool.commonPool-worker-7"                   Exception in thread "ForkJoinPool.commonPool-worker-4" Exception in thread "ForkJoinPool.commonPool-worker-2" Exception in thread "ForkJoinPool.commonPool-worker-3" Exception in thread "ForkJoinPool.commonPool-worker-10"                   java.lang.SecurityException: setContextClassLoader

Exception in thread "ForkJoinPool.commonPool-worker-11" Exception in thread "ForkJoinPool.commonPool-worker-9" 	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-03-18 15:23:05,196 ERROR [io.qua.run.boo.ForkJoinClassLoading] (main) Timed out trying to set fork join ClassLoader, this should never happen unless something has tied up a fork join thread before the app launched

2024-03-18 15:23:05,745 INFO  [io.quarkus] (Quarkus Main Thread) rest-client-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.8.2) started in 2.822s. Listening on: http://localhost:8080
2024-03-18 15:23:05,747 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-03-18 15:23:05,747 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-client, resteasy-client-jackson, resteasy-jackson, resteasy-mutiny, smallrye-context-propagation, vertx]
```

### Expected behavior

No exceptions.

### Actual behavior

Exception thrown:

```
java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading$1.run(ForkJoinClassLoading.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1494)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2038)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
```

### How to Reproduce?

Reproducer:

Get and extract a JDK 23+14 build. E.g. for `Linux` on `x86_64` using:
```
$ wget -O jdk.tar.gz https://api.adoptium.net/v3/binary/version/jdk-23+14-ea-beta/linux/x64/jdk/hotspot/normal/adoptium
$ tar -xf jdk.tar.gz
$ ./jdk-23+14/bin/java --version
openjdk 23-beta 2024-09-17
OpenJDK Runtime Environment Temurin-23+14-202403142003 (build 23-beta+14-ea)
OpenJDK 64-Bit Server VM Temurin-23+14-202403142003 (build 23-beta+14-ea, mixed mode, sharing)
```

```
$ git clone https://github.com/quarkusio/quarkus-quickstarts.git
$ cd quarkus-quickstarts/rest-client-quickstart
$ JAVA_HOME=/path/to/jdk-23+14 ./mvnw quarkus:dev
```

### Additional information

This is caused by https://bugs.openjdk.org/browse/JDK-8327501 which is new in JDK 23+14.

**Comment by jerboaa** [comment]
FWIW, reproducer steps work fine with `JDK 23+13`

**Comment by jerboaa** [comment]
We now also see this in native integration tests for:
`Integration Tests - Amazon Lambda AWS Gateway REST API`

Looks like this:
```
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:169)
	... 27 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 30 more
Caused by: java.lang.SecurityException: setContextClassLoader
	at java.base/java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread.setContextClassLoader(ForkJoinWorkerThread.java:232)
	at io.quarkus.smallrye.openapi.runtime.OpenApiRecorder.classLoaderHack(OpenApiRecorder.java:72)
	at io.quarkus.deployment.steps.SmallRyeOpenApiProcessor$classLoaderHack1558305429.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.SmallRyeOpenApiProcessor$classLoaderHack1558305429.deploy(Unknown Source)
	... 31 more
```

See: https://github.com/graalvm/mandrel/actions/runs/8384081617/job/22961614119#step:12:676

Should be fixed once https://bugs.openjdk.org/browse/JDK-8328366 integrates and propagates to an EA build.

**Comment by jerboaa** [comment]
Update [JDK-8328366](https://bugs.openjdk.org/browse/JDK-8328366) is fixed upstream and the next build promotion and EA builds (probably next week) should no longer show this issue.

**Comment by geoand** [comment]
Is this still an issue or can we close it?

**Comment by jerboaa** [comment]
@geoand No longer an issue. Feel free to close. The fix is in JDK `23+18` and better.

**Comment by geoand** [comment]
Excellent, thanks for the update!

**Comment by snazy** [comment]
I still see this issue, even with the latest Java version 23.0.2 (that should have [JDK-8328366](https://bugs.openjdk.org/browse/JDK-8328366)). /cc @geoand

**Comment by snazy** [comment]
Feels like it's okay to leave the `ForkJoinClassLoading`, but maybe surround `Thread.currentThread().setContextClassLoader(classLoader);` with a silent catch for `SecurityException`? If `SecurityException` is thrown, it (nowadays) means that the argument wasn't the system class loader.
Maybe also extend the timeout for the call to `allDone.await` to something quite higher, as busy/"overloaded" systems (hello GH runners) may take a bit longer.

**Comment by jerboaa** [comment]
> I still see this issue, even with the latest Java version 23.0.2 (that should have [JDK-8328366](https://bugs.openjdk.org/browse/JDK-8328366)). 

@snazy How would I be able to reproduce? I'm using the steps in https://github.com/quarkusio/quarkus/issues/39526#issue-2192388187

```
$ /disk/openjdk/builds/jdk-23.0.2+7/bin/java --version
openjdk 23.0.2 2025-01-21
OpenJDK Runtime Environment Temurin-23.0.2+7 (build 23.0.2+7)
OpenJDK 64-Bit Server VM Temurin-23.0.2+7 (build 23.0.2+7, mixed mode, sharing)
$ JAVA_HOME=/disk/openjdk/builds/jdk-23.0.2+7 ./mvnw quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.acme:rest-client-quickstart >-------------------
[INFO] Building rest-client-quickstart 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus:3.19.2:dev (default-cli) @ rest-client-quickstart ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ rest-client-quickstart
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Invoking quarkus:3.19.2:generate-code (default) @ rest-client-quickstart
[INFO] Invoking compiler:3.11.0:compile (default-compile) @ rest-client-quickstart
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ rest-client-quickstart
[INFO] Copying 1 resource from src/test/resources to target/test-classes
[INFO] Invoking quarkus:3.19.2:generate-code-tests (default) @ rest-client-quickstart
[INFO] Invoking compiler:3.11.0:testCompile (default-testCompile) @ rest-client-quickstart
[INFO] Nothing to compile - all classes are up to date
[WARNING] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] org.opentest4j:opentest4j::jar classpath entry /home/sgehwolf/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar was overriden with /home/sgehwolf/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2025-03-11 11:09:27,842 INFO  [io.quarkus] (Quarkus Main Thread) rest-client-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.19.2) started in 1.240s. Listening on: http://localhost:8080

2025-03-11 11:09:27,845 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2025-03-11 11:09:27,846 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, rest, rest-client, rest-client-jackson, rest-jackson, smallrye-context-propagation, vertx]
2025-03-11 11:09:50,134 INFO  [io.quarkus] (Shutdown thread) rest-client-quickstart stopped in 0.004s

--

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.797 s
[INFO] Finished at: 2025-03-11T11:09:50+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by snazy** [comment]
Example run [is here](https://github.com/apache/polaris/actions/runs/13784175114/job/38548264144?pr=1156), in "Code style checks and tests" around [this line 549](https://github.com/apache/polaris/actions/runs/13784175114/job/38548264144?pr=1156#step:5:550) - it's logging the consequence.

**Comment by snazy** [comment]
@jerboaa that message means, that the FJ threads failed to call `setContextClassLoader` and did not reach `allDone.countDown()`

**Comment by jerboaa** [comment]
> [@jerboaa](https://github.com/jerboaa) that message means, that the FJ threads failed to call `setContextClassLoader` and did not reach `allDone.countDown()`

It feels like this would need a separate issue. Please open one with a reproducer, thanks!
