### ISSUE TITLE
Application won't start when using hibernate select query with custom class

### ISSUE THREAD

**Issue by esorio** [quarkusio/quarkus#41307]
### Describe the bug

Hi,
I have a project with the hibernate-orm extension, there is an entity class (that extends a base class) with a named query defined in this way.

`SELECT new org.acme.MyEntityDto(e.id, e.field) FROM MyEntity e`

### Expected behavior

The application starts.

### Actual behavior

The application fails with the following error:
`Caused by: org.hibernate.query.NamedQueryValidationException: Errors in named queries: 
  [1] Error in query named 'findMyEntity': Missing constructor for type 'MyEntityDto' [SELECT new org.acme.MyEntityDto(e.id, e.field) FROM MyEntity e]`

### How to Reproduce?

Steps to reproduce the problem:

* check-out the reproducer https://github.com/esorio/quarkus-hibernate-select-class
* start the application using `./gradlew quarkusDev`

The error occurs with Quarkus version 3.11.2, while Quarkus 3.10.2 everything is ok.

### Output of `uname -a` or `ver`

Linux 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC 

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by gsmet** [comment]
Does it work if you get rid of the base class and the generics for `id` or you have the same issue?

**Comment by esorio** [comment]
> Does it work if you get rid of the base class and the generics for `id` or you have the same issue?

Yes, I just tried... if I remove the use of generics for the `id` it works

**Comment by david-cabillic** [comment]
Same issue using a **record** class with no ID in constructor. It's working in non-native mode. Will you fix this?

**Comment by mbladel** [comment]
@david-cabillic this sounds like https://hibernate.atlassian.net/browse/HHH-18218, which was resolved in Hibernate's 6.6 version, included in Quarkus since version 3.14. I've checked out your reproducer and verified that the latest Quarkus versions cause no problem with your instantiation query, so I would suggest upgrading as soon as possible.

**Comment by david-cabillic** [comment]
@mbladel I'm using Quarkus 3.17.4.

**Comment by mbladel** [comment]
@david-cabillic then you're probably facing a different problem, one that only happens in native mode. Please create a simple reproducer project and create a separate issue.

**Comment by geoand** [comment]
Is the original issue still a problem with the latest versions of Quarkus?

**Comment by geoand** [comment]
Can anyone comment on my question above?

**Comment by esorio** [comment]
Sorry for the delay!
I just checked with the latest Quarkus release (3.19.2), and the problem is no longer present.

**Comment by geoand** [comment]
Great, thanks a lot!
