### ISSUE TITLE
Header Propagation does not work when using Asynchronous Rest Clients

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#4404]
**Describe the bug**
Rest Client Header Propagation does not work when using Asynchronous Rest Clients. I have created a small sample which reproduces the problem with Quarkus 0.23.2, with both `CompletionStage` and `Single`

[Archive.zip](https://github.com/quarkusio/quarkus/files/3696314/Archive.zip)

**Expected behavior**
When using `Single` or `CompletionStage` in the REST clients' responses, it seems that the header propagation does not work.

**Actual behavior**
when `HeaderPropagator` is called, the container request headers are empty.

**To Reproduce**
1. Open the attached project and run it. Put a breakpoint inside the `HeaderPropagator`
2. GET `http://0.0.0.0:8080/hello`. The breakpoint will get hit, the `containerRequestHeaders` will be full of your browser's headers.
3. GET `http://0.0.0.0:8080/hello/async` or `http://0.0.0.0:8080/hello/single`. The same array will be empty.

I have also included all necessary libraries as instructred here https://quarkus.io/guides/context-propagation-guide and had the same results. Header propagation only works in synchronous mode.

**Comment by kenfinnigan** [comment]
The issue is that https://github.com/quarkusio/quarkus/blob/master/extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/IncomingHeadersProvider.java#L28 returns `null` because the context data is held in a `ThreadLocal`.

With a sync call, we're on the same thread, a worker thread, but when using `CompletionStage` we're on a separate thread which is why it's empty.

@FroMage any thoughts on where/how to propagate the `ThreadLocal` for RESTEasy context data?

**Comment by FroMage** [comment]
The headers of what? I thought client calls had no context _at all_. The spec says:

> Except for Configuration and Providers, which are injectable in both client and server-side providers, all the other types are server-side only.

So `HttpRequest` is server-side and should not be visible in clients and if they are visible it's by accident and they point to the server's request (when the client is running in a jax-rs server endpoint).

**Comment by kenfinnigan** [comment]
When it's used on its own, then yes.

When REST Client is used inside a JAX-RS endpoint, it's possible for the headers to be propagated from that incoming request to the REST Client call

**Comment by FroMage** [comment]
OK, so you're intentionally propagating server request headers to the client request headers. Fine. Then if you want to capture the headers I suggest you do it when you still have access to them, at the time you do the request, and not when you get the answer on another thread. 

I'm not sure if you want to propagate the contexts inside the client, so that any users of the async pipeline will get them, or if you want to leave that choice to its users.

But for your specific use-case I suggest capturing the HttpHeaders value at the time you make the async request, instead of later on, on a random thread that doesn't have context.

**Comment by kenfinnigan** [comment]
It does capture them on the initial thread, but it stores them into RESTEasy Context which then stores them in a `ThreadLocal`.

So it's a question of what's the best approach to propagating it between threads

**Comment by FroMage** [comment]
Huh. If this is RESTEasy client stuff then I'd say perhaps. If it's MP client stuff I'd say no: just store it and associate it with the request. You don't need to store/retreive it from the context once it's captured.

**Comment by kenfinnigan** [comment]
It's the MP Client impl in RESTEasy.

I'm being dense here, but what do you mean by "store it and associate it with the request"? I'm not connecting the dots as to how it gets on the worker pool thread for the REST Client call?

**Comment by FroMage** [comment]
Damnit, it has two clients, I never noticed that.

**Comment by FroMage** [comment]
So that resteasy-client-microprofile doesn't mention context _at all_, which is even worse than resteasy-client, which uses the server context by accident. But since it depends on resteasy-client, it's probably affected as well. That's nasty.

**Comment by kenfinnigan** [comment]
So I'm not totally crazy then?

So you're saying this is also related to the RESTEasy issue you raised the other day? Initially, I thought it was, but then for some reason decided it wasn't

**Comment by FroMage** [comment]
Well, here you're apparently not getting a context at all, which is different to the issue I saw where it reuses the server context.

**Comment by kenfinnigan** [comment]
right, because it's not present on the new thread.

Ok will raise a separate issue

**Comment by FroMage** [comment]
But generally, here you're relying on having a context during `getIncomingHeaders` and I wonder which thread this runs on and who created it. If it's RESTEasy who created the thread, then it's probably its responsability to propagate the context. If it's MP, then it's MP's fault ;)

**Comment by kenfinnigan** [comment]
From the debugging I did, it's called on the Vert.x event loop, then the REST Client call is farmed out to a worker thread because it uses `CompletionStage`.

So it's kind of straddling Quarkus and RESTEasy/MP worlds

**Comment by FroMage** [comment]
farmed out to a worker thread?

**Comment by FroMage** [comment]
that doesn't make any sense, it's far more likely that CS/async calls can run on the IO thread

**Comment by FroMage** [comment]
It's non-CS/async that can never run on the IO thread and need to run on workers

**Comment by kenfinnigan** [comment]
That's not what I saw when debugging the reproducer, at least from what I recall yesterday afternoon

**Comment by FroMage** [comment]
so who farms it out? What source file should I be looking at?

**Comment by kenfinnigan** [comment]
I think it's "farmed out" by the async invoker in RESTEasy MP Client, as it specifies an Executor, but I presume our RESTEasy integration means it's getting threads from the underlying Vert.x worker pool for it.

I may need to retry the reproducer and dig deeper

**Comment by kenfinnigan** [comment]
All the MP REST Async bits are in: https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/async

**Comment by FroMage** [comment]
huh, looks to me like AsyncInvocationInterceptor/prepareContext could deal with context propagation ;)

**Comment by FroMage** [comment]
But in any case if you expect to be able to run things on executors and those things should have access to server contexts, such as resteasy/cdi/transaction, then you will just need to use MP-CP.

**Comment by FroMage** [comment]
I mean: is `IncomingHeadersProvider.java` a special case or can we have more filter/interceptor/providers that get invoked on this thread which will expect resteasy/cdi/transaction/servlet contexts to be set up?

**Comment by FroMage** [comment]
Generally we need to figure out who is responsible for setting up those contexts. Probably an issue needs to be opened and a meeting needs to be had. But in any case, if we end up fixing this for the RESTEasy context, we won't get cdi/transaction/servlet contexts for free without MP-CP.

**Comment by kenfinnigan** [comment]
In theory, it's possible that there is an expectation that the various contexts are available for injection/use.

I agree we need to figure this out. Will open a Quarkus issue, and try to set up a meeting.

**Comment by FroMage** [comment]
Thanks. Will need Alessio and Bill and whoever wrote the SR rest client (you?).

**Comment by kenfinnigan** [comment]
I think Michal did the async bits, but it's going to need several people for sure

**Comment by FroMage** [comment]
OK I have made progress with testing this and I can say that the client does have a context, and it's properly clear of the server context at this point, which is good news because that's what it should do, but it's bad news for you because at the point where you collect the server's request headers it's already too late: they're gone.

IMO the fact that this works in the non-async version is a bug to me: the context should be cleared at this point, and I should work to fix this.

Now, @kenfinnigan you said:

> It does capture them on the initial thread

Can you point me where this is done?

**Comment by FroMage** [comment]
I think there's a complex problem between "we want to propagate contexts to the client's async callbacks" and "we should not confuse the server and client contexts".

We can explain the problem here:

```java
@GET
public CompletionStage<String> server(){
 return restclient.client().thenApply(v -> {
  // we want server or client context here?
  return v;
 };
}
```

I guess for the user it's pretty intuitive that the server context applies here, because for non-jax-rs (CDI, transaction etc) it's obvious and the same context anyway, and for jax-rs the only context that the client should have is `Providers` and `Configuration` which is nowhere near enough to do server stuff: remember that all `@Context` injected types such as `UriBuilder` are proxies that look instances up lazily via the context, so if we use the client context in this callback then any calls to `UriBuilder` will throw.

But at the same time, any client interceptor/filter should be completely isolated from the server context.

Except the filter which captures the incoming request headers. That one's a shrodinger's filter.

**Comment by FroMage** [comment]
BTW, I wonder if it's not generally a super bad idea to enable header propagation by default, unless they're filtered to a minimum. Isn't that a security risk?

**Comment by csotiriou** [comment]
@FroMage Just a suggestion:

As a use case, I believe that enabling header propagation by default is going to be a security risk. The reason why many use cases generally want header propagation is to support distributed logging. But enabling header propagation by default (which means all headers are propagated) will send probably some unwanted headers down the chain (possibly authentication tokens), so one will have to do extra work to prevent that.

**Comment by FroMage** [comment]
OK, it looks like header propagation is not on by default, because users need to have an explicit `ClientHeadersFactory` implementation to enable it, and they can pick which ones they propagate, so I think it's acceptable.

I've a fix for this in RESTEasy.

**Comment by FroMage** [comment]
BTW, I've decided to not propagate all contexts automatically because this doesn't require all contexts, and we can tackle this later.

**Comment by FroMage** [comment]
Fix in https://github.com/resteasy/Resteasy/pull/2238.

**Comment by FroMage** [comment]
Fixed upstream, leaving open until they release and we can upgrade.

**Comment by gorshkov-leonid** [comment]
I reproduced it with the latest quarkus 1.13

**Comment by gorshkov-leonid** [comment]
e.g.:

client.doOperation1().thenComposeAsync((v)->client.doOperation2() ,ex)
* Operation1 is 200
* Operation 2 is 401 (because of absence of header)

It seems thatResteasyContext is not accessible on chain in the first thenCompose:
`ResteasyContext.getContextData(javax.ws.rs.core.HttpHeaders.class).getRequestHeader("Authorization").get(0)`

**Comment by geoand** [comment]
Is this still an issue? Furthermore, is it an issue with the new `quarkus-rest-client-reactive`?

**Comment by jdussouillez** [comment]
Still happening with Quarkus v2.12.3. We are migrating our Quarkus app in reactive and we have a NullPointerException when calling a Jersey REST client because the headers are null ([NPE is thrown in this call because `responseContext.getHeaders()` returns null](https://github.com/zhengchaobin/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/logging/ClientLoggingFilter.java#L128)).

Do you guys have any workaround ?

**Comment by geoand** [comment]
Is this an issue with `quarkus-rest-client-reactive` or with `quarkus-rest-client`?

**Comment by jdussouillez** [comment]
@geoand Yes it is, we are migrating from `quarkus-rest-client` to `quarkus-rest-client-reactive`. So basically we replaced the non-reactive dependency with the reactive one in our pom.xml and then we are checking the impacts.

**Comment by geoand** [comment]
Do you have a sample application we can check to see the problem in action?

**Comment by jdussouillez** [comment]
@geoand I will work on this and try to provide you the smallest project to reproduce next week.

**Comment by geoand** [comment]
I am going to close this as did not get a reproducer.

If this still is an issue and a reproducer becomes available, we will certainly look into.

**Comment by jdussouillez** [comment]
I can confirm this problem still exists on Quarkus v3.0.4 but it's kind of random. And of course it works fine when I try to reproduce it in a small project.

It get random NPE errors when using a custom filter which looks like:

```java
@ApplicationScoped
public class MyCustomFilter implements ResteasyReactiveClientRequestFilter, ResteasyReactiveClientResponseFilter {


    @Override
    public void filter(final ResteasyReactiveClientRequestContext reqContext) {
        // ...
    }

    @Override
    public void filter(final ResteasyReactiveClientRequestContext reqContext, final ClientResponseContext respContext) {
        var contentEncoding = respContext.getHeaderString(HttpHeaders.CONTENT_ENCODING); // NPE
        if (contentEncoding == null) {
            return;
        }
        // ...
    }
}
```

Stacktrace I get in Grafana:
```
    {
        "exception": {
            "refId": 1,
            "exceptionType": "jakarta.ws.rs.ProcessingException",
            "message": "java.lang.NullPointerException: Cannot invoke \"jakarta.ws.rs.core.MultivaluedMap.get(Object)\" because \"headers\" is null",
            "frames": [
                {
                    "class": "org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler",
                    "method": "handle",
                    "line": 25
                },
                {
                    "class": "org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler",
                    "method": "handle",
                    "line": 10
                },
                {
                    "class": "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext",
                    "method": "invokeHandler",
                    "line": 229
                },
                {
                    "class": "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext",
                    "method": "run",
                    "line": 145
                },
                {
                    "class": "org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1",
                    "method": "lambda$execute$0",
                    "line": 295
                },
                {
                    "class": "io.vertx.core.impl.ContextInternal",
                    "method": "dispatch",
                    "line": 264
                },
                {
                    "class": "io.vertx.core.impl.ContextInternal",
                    "method": "dispatch",
                    "line": 246
                },
                {
                    "class": "io.vertx.core.impl.EventLoopContext",
                    "method": "lambda$runOnContext$0",
                    "line": 43
                },
                {
                    "class": "io.netty.util.concurrent.AbstractEventExecutor",
                    "method": "runTask",
                    "line": 174
                },
                {
                    "class": "io.netty.util.concurrent.AbstractEventExecutor",
                    "method": "safeExecute",
                    "line": 167
                },
                {
                    "class": "io.netty.util.concurrent.SingleThreadEventExecutor",
                    "method": "runAllTasks",
                    "line": 470
                },
                {
                    "class": "io.netty.channel.nio.NioEventLoop",
                    "method": "run",
                    "line": 566
                },
                {
                    "class": "io.netty.util.concurrent.SingleThreadEventExecutor$4",
                    "method": "run",
                    "line": 997
                },
                {
                    "class": "io.netty.util.internal.ThreadExecutorMap$2",
                    "method": "run",
                    "line": 74
                },
                {
                    "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
                    "method": "run",
                    "line": 30
                },
                {
                    "class": "java.lang.Thread",
                    "method": "run"
                }
            ],
            "causedBy": {
                "exception": {
                    "refId": 2,
                    "exceptionType": "java.lang.NullPointerException",
                    "message": "Cannot invoke \"jakarta.ws.rs.core.MultivaluedMap.get(Object)\" because \"headers\" is null",
                    "frames": [
                        {
                            "class": "org.jboss.resteasy.reactive.common.headers.HeaderUtil",
                            "method": "getHeaderString",
                            "line": 197
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.client.impl.ClientResponseContextImpl",
                            "method": "getHeaderString",
                            "line": 74
                        },
                        {
                            "class": "com.myapp.api.filter.MyCustomFilterFilter",
                            "method": "filter",
                            "line": 49
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientResponseFilter",
                            "method": "filter",
                            "line": 10
                        },
                        {
                            "class": "com.myapp.api.filter.MyCustomFilterFilter_ClientProxy",
                            "method": "filter"
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler",
                            "method": "handle",
                            "line": 21
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler",
                            "method": "handle",
                            "line": 10
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext",
                            "method": "invokeHandler",
                            "line": 229
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext",
                            "method": "run",
                            "line": 145
                        },
                        {
                            "class": "org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1",
                            "method": "lambda$execute$0",
                            "line": 295
                        },
                        {
                            "class": "io.vertx.core.impl.ContextInternal",
                            "method": "dispatch",
                            "line": 264
                        },
                        {
                            "class": "io.vertx.core.impl.ContextInternal",
                            "method": "dispatch",
                            "line": 246
                        },
                        {
                            "class": "io.vertx.core.impl.EventLoopContext",
                            "method": "lambda$runOnContext$0",
                            "line": 43
                        },
                        {
                            "class": "io.netty.util.concurrent.AbstractEventExecutor",
                            "method": "runTask",
                            "line": 174
                        },
                        {
                            "class": "io.netty.util.concurrent.AbstractEventExecutor",
                            "method": "safeExecute",
                            "line": 167
                        },
                        {
                            "class": "io.netty.util.concurrent.SingleThreadEventExecutor",
                            "method": "runAllTasks",
                            "line": 470
                        },
                        {
                            "class": "io.netty.channel.nio.NioEventLoop",
                            "method": "run",
                            "line": 566
                        },
                        {
                            "class": "io.netty.util.concurrent.SingleThreadEventExecutor$4",
                            "method": "run",
                            "line": 997
                        },
                        {
                            "class": "io.netty.util.internal.ThreadExecutorMap$2",
                            "method": "run",
                            "line": 74
                        },
                        {
                            "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
                            "method": "run",
                            "line": 30
                        },
                        {
                            "class": "java.lang.Thread",
                            "method": "run"
                        }
                    ]
                }
            }
        }
    }
```

**Comment by csotiriou** [comment]
Sorry to jump in, but I would like to clarify that my original comment and report concerned the non-reactive rest client (there was no reactive resteasy back then), and the usage of `ClientHeadersFactory`, which is the "proper" way of doing header propagation (get headers from the incoming request, and put them in the outbound requests from the microservice).

This seems to be a different issue, @jdussouillez , unless I am mistaken.

Also, from what I can understand, the `respContext.getHeaderString(HttpHeaders.CONTENT_ENCODING);` will return the response headers from the server that gave the response to the rest-client's HTTP request, which may not have something to do with the headers of the incoming request to the microservice.
