### ISSUE TITLE
HTTP Compression still not working with quarkus-amazon-lambda-rest dependency

### ISSUE THREAD

**Issue by mirko-ruggiero** [quarkusio/quarkus#47028]
### Describe the bug

HTTP  response compression not working in the REST API if `quarkus-amazon-lambda-rest` maven dependency is added to POM.
Removing the dependency from the POM, the compression works just fine

### Expected behavior

Response should be GZIP compressed
Response header `Content-Encoding: gzip` expected

### Actual behavior

No compression and no header

### How to Reproduce?

Reproducer :
[reproducer.zip](https://github.com/user-attachments/files/19483117/reproducer.zip)

mvn clean compile quarkus:dev
curl -v -i -H "Accept-Encoding: gzip" "http://localhost:8080/hello/"
curl -v -i -H "Accept-Encoding: gzip" "http://localhost:8080/hello/response"

see how response is not compressed and no header is present
remove `quarkus-amazon-lambda-rest` from POM and rebuild and see how response gets compressed and header is present

### Output of `uname -a` or `ver`

Linux ********** 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.6" 2025-01-21 OpenJDK Runtime Environment (build 21.0.6+7-Ubuntu-124.04.1) OpenJDK 64-Bit Server VM (build 21.0.6+7-Ubuntu-124.04.1, mixed mode, sharing)

### Quarkus version or git rev

3.21.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Java version: 21.0.6, vendor: Ubuntu, runtime: /usr/lib/jvm/java-21-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.11.0-19-generic", arch: "amd64", family: "unix"

### Additional information

properties to enable compression:
```
quarkus.http.enable-compression=true
quarkus.http.compress-media-types=application/json,text/html
```
Same issue has been raised in the past ([see here](https://github.com/quarkusio/quarkus/issues/34472))

**Comment by gsmet** [comment]
Yeah, I can see why this is happening. I'll have a look.

**Comment by gsmet** [comment]
I had a look at this one last week.

From what I can see, the Lambda handler doesn't get a compressed output from Quarkus REST but I haven't yet figured out exactly why.

**Comment by mirko-ruggiero** [comment]
Thanks for looking into it, looking forward to further updates

**Comment by mirko-ruggiero** [comment]
Hello, any update on this?

**Comment by gsmet** [comment]
@geoand ah yes sorry, totally missed your ping :). I had a look back in the days and I think it might have the same root causes as the other issue you fixed in this area.

**Comment by geoand** [comment]
🙏🏽 

@mirko-ruggiero do you know if this issue persists with Quarkus 3.26?

**Comment by gsmet** [comment]
I meant this PR: https://github.com/quarkusio/quarkus/pull/47860 . Not entirely sure but it looked related things not being correctly propagated.

**Comment by mirko-ruggiero** [comment]
> 🙏🏽
> 
> [@mirko-ruggiero](https://github.com/mirko-ruggiero) do you know if this issue persists with Quarkus 3.26?

yes, I can still reproduce the issue with the the same reproducer, just increasing the version in the pom

**Comment by geoand** [comment]
I see, thanks. I'll take a look hopefully next week.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/49833 fixes the issue
