### ISSUE TITLE
org.mvnpm:lit:[3.1.3,3.2) range version dependency doesn't work

### ISSUE THREAD

**Issue by dbatyuk** [quarkusio/quarkus#47347]
### Describe the bug

Looks like there is issue with new https://repo.maven.apache.org/maven2/org/mvnpm/lit/maven-metadata.xml where it only lists 2.0.1 version while there are other versions https://repo.maven.apache.org/maven2/org/mvnpm/lit/. It breaks quarkus 3.15.4 because it uses range dependecy

**Comment by phillip-kruger** [comment]
see https://github.com/mvnpm/mvnpm/issues/20500

We are in communication with Maven central w.r.t this.

As a workaround you can add the mvnpm server repo

To use it in your local Maven settings add the following to your settings.xml (typically /home/your-username/.m2/settings.xml)

<settings>
    <profiles>
        <profile>
            <id>mvnpm-repo</id>
            <repositories>
                <repository>
                    <id>central</id>
                    <name>central</name>
                    <url>https://repo.maven.apache.org/maven2</url>
                </repository>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>mvnpm.org</id> 
                    <name>mvnpm</name>
                    <url>https://repo.mvnpm.org/maven2</url>
                </repository>
            </repositories>
        </profile>
    </profiles>

    <activeProfiles>
        <activeProfile>mvnpm-repo</activeProfile>
    </activeProfiles>

</settings>

**Comment by cristianovagos** [comment]
Same here on 3.15.2

**Comment by arnauhortelano** [comment]
Same @cristianovagos

**Comment by phillip-kruger** [comment]
@arnauhortelano @cristianovagos  Please use the workaround until it's fixed in central.

**Comment by dbatyuk** [comment]
@phillip-kruger it looks like using https://repo.mvnpm.org/maven2 doesn't help as for example https://repo.mvnpm.org/maven2/org/mvnpm/lit/3.1.4/lit-3.1.4.pom states `Package 'org.mvnpm:lit:3.1.4' is already synced on Maven Central.`

**Comment by quotidian-ennui** [comment]
The suggestion that I put in for dependency-resolution is working for quarkus-3.15.4 (as of 12:00 BST) : https://github.com/mvnpm/mvnpm/issues/20500#issuecomment-2801006209 in so far that I don't have to `gradle --offline`

What I did to figure out the correct string was to do a `gradle -Dorg.gradle.console=plain dependencies | grep "org\.mvnpm:lit"` to figure out what it was trying to resolve and then for substitute that. Yours might vary depending on your quarkus version / quarkiverse versioning.

**Comment by phillip-kruger** [comment]
> [@phillip-kruger](https://github.com/phillip-kruger) it looks like using https://repo.mvnpm.org/maven2 doesn't help as for example https://repo.mvnpm.org/maven2/org/mvnpm/lit/3.1.4/lit-3.1.4.pom states `Package 'org.mvnpm:lit:3.1.4' is already synced on Maven Central.`

O yes. This will fall back to central once we synced. Let me see if I can create a workaround in mvnpm. I'll let you know here.

**Comment by phillip-kruger** [comment]
This is now fixed by cenrtal.

**Comment by sfgho** [comment]
same for me on quarkus 3.15.2

**Comment by ASURA-RD** [comment]
i tried downgrading and its working fine with 3.11.3 and i was able to build

**Comment by ASURA-RD** [comment]
Resolved the issue after upgrading to 3.16.1

**Comment by temofey1989** [comment]
Not working for `3.15.4`...

**Comment by umutsahin** [comment]
Still not working for me as well - `3.15.2`

Using mulesoft repo - "https://repository.mulesoft.org/nexus/content/repositories/public/"

As a workaround for those who are stuck as me

**Comment by levimartines** [comment]
for those who are still facing this issue, try manually download the artifact 
`mvn dependency:get -Dartifact=org.mvnpm:lit:3.1.3`
and add mavenLocal() to build.gradle repositories

**Comment by 1Wggb1** [comment]
Maybe enforced dependency can solve the problem.

Example in gradle:
```
#build.gradle
...
implementation enforcedPlatform('org.mvnpm:lit:3.xy')
...
```

**Comment by uroshekic** [comment]
Thank you , I've added `--refresh-dependencies` to `gradle build` and forcing refresh of dependencies helped.

**Comment by phillip-kruger** [comment]
We paused mvnpm syncing to central for the time being, so at least we can not break it again
