### ISSUE TITLE
Environment Variable Configuration Issues since Quarkus 3.23.3

### ISSUE THREAD

**Issue by wiebeck** [quarkusio/quarkus#48347]
### Describe the bug

We noticed that Quarkus 3.23.3 introduced issues with reading configuration from enviromment variables under certain circumstances.

In short: it seems to affect `@ConfigMapping` annotated interfaces containing maps. Environment variables that should configure the interface are not picked up if the project also contains the Quarkus Vault extension.

The workaround is to **either remove the Vault extension** or to **downgrade `smallrye-config`** to version 3.13.0 (Quarkus 3.23.3 uses 3.13.1), so both components somehow don't play nice with each other.

See the reproducer for more information.

### Expected behavior

The expected behavior is that Quarkus picks up the environment variables and maps them properly to the `@ConfigMapping` annotated interface. so that your app can access the configuration.

### Actual behavior

Environment variables are not being picked up leaving the `@ConfigMapping` annotated interface unpopulated leading to missing configuration.

### How to Reproduce?

Of course I can provide a reproducer with detailed instructions here: https://github.com/wiebeck/quarkus-3.23.3-config-mapping-bug

### Output of `uname -a` or `ver`

Linux (container image), Mac

### Output of `java -version`

21

### Quarkus version or git rev

3.23.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.31 (irrelevant)

### Additional information

This issue appeared first in Quarkus 3.23.3 and is probably related to smallrye-config 3.13.1 and maybe quarkus-vault. I personally wouldn't rule out that other Quarkus extensions also affect this behavior.

**Comment by radcortez** [comment]
I'll have a look.

**Comment by wiebeck** [comment]
Thanks @radcortez!

**Comment by toniwe** [comment]
In our case the following env vars also did not work in 3.23.3 when using `@Inject TlsConfigurationRegistry certificates;`

```
QUARKUS_TLS_TRUST_STORE_JKS_PATH
QUARKUS_TLS_TRUST_STORE_JKS_PASSWORD
```
Setting them via application.yaml / application.properties instead works though.

(java 21, gradle)

**Comment by gsmet** [comment]
@radcortez can you confirm your fix should fix this issue too?

**Comment by radcortez** [comment]
Most likely, but without a proper reproducer, we cannot be sure. 

The issue was caused by a combination of dependencies and how the Vault extension does some things. @toniwe can you get us a reproducer?

**Comment by wiebeck** [comment]
Using my simple reproducer (see original post) I confirmed that smallrye-config 3.13.2 in fact gives the expected results.

**Comment by radcortez** [comment]
> Using my simple reproducer (see original post) I confirmed that smallrye-config 3.13.2 in fact gives the expected results.

Thanks!

**Comment by kdurnoga** [comment]
@gsmet It looks like changing configuration settings with dashes in their names via environment variables is still broken. At least it does not work in conjunction with smallrye-messaging, when I try to set `mp.messaging.outgoing.some-channel-name.enabled` with `MP_MESSAGING_OUTGOING_SOME_CHANNEL_NAME_ENABLED=true` - the runtime complains about 
```
Invalid channel configuration -  the `connector` attribute must be set for channel `some`
```
This worked in Quarkus **3.22.3**, but fails after upgrading to **3.23.4**.

Edit: I do have the `connector` attribute set for the channel `some-channel-name` in my `application.properties` file.

**Comment by radcortez** [comment]
@kdurnoga Can you please provide a reproducer? Thank you.
