### ISSUE TITLE
built-in ExceptionMappers cause unexpected behavior

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7883]
**Describe the bug**
Quarkus includes several JAX-RS `ExceptionMapper`s out of the box. Those are actually not considered built-in as per the JAX-RS specification, they are just built into Quarkus to improve user experience.

However, they can also make the user experience worse. For example, if I create an `ExceptionMapper` for all `Exception`s, it _isn't_ used if I throw a JAX-RS `NotFoundException`, because Quarkus includes an exception mapper for it (`NotFoundExceptionMapper`). Per the JAX-RS specification, RESTEasy will "use the provider whose generic type is the nearest superclass of the exception."

For example, if my application communicates using JSON and my exception mapper produces some meaningful JSON structure for all `Exception`s, I get an empty response body for `NotFoundException` (which is what `io.quarkus.resteasy.runtime.NotFoundExceptionMapper` does for JSON). It took me a while to figure out what's going on here.

As a workaround, I have to create my own `NotFoundExceptionMapper`.

**Expected behavior**
My own generic exception mapper is used.

**Actual behavior**
Quarkus "built-in" exception mapper is used, because it targets a more specific exception.

I understand this is kinda by design, but unexpected still. I don't know if it would help or not if RESTEasy would consider the "built-in" exception mappers in Quarkus as actually built-in per JAX-RS spec.

**To Reproduce**
1. Add an implementation of `ExceptionMapper<Exception>`.
2. Throw `NotFoundException`.
3. Observe that my own exception mapper is not used.

**Comment by Ladicek** [comment]
Not sure who to CC, perhaps @asoldano?

**Comment by geoand** [comment]
cc @FroMage

**Comment by FroMage** [comment]
Yeah, something we need to fix.

**Comment by sberyozkin** [comment]
May be a property like `disable-quarkus-mappers` ? Otherwise it can be tricky if not impossible, as both the quarkus and the custom user mapper are all the custom providers for RestEasy, both competing for the same exception type

**Comment by sberyozkin** [comment]
The other option is to check in Quarkus, before registering its own mapper if something else is available, but then Quarkus would need some RestEasy logic to see if the user mapper is competing with the Quarkus one or not...May be just checking the type var would be enough

**Comment by Ladicek** [comment]
@sberyozkin I don't understand JAX-RS, but would it help if RESTEasy treated the Quarkus providers as "built-in"? That's what they are, from my perspective. (Not sure if that wouldn't break something else :grin:)

**Comment by sberyozkin** [comment]
@Ladicek Hi, then RestEasy would need to decide what to with its built-in mappers if any, though it might work nicely, indeed Alessio and other RestEasy gurus would know :-)

**Comment by FroMage** [comment]
Actually, the spec doesn't talk about built-ins when it discusses `ExceptionMapper`, and the implementation seems to only favour non-built-ins when comparing exceptions by class.

So even if the priority would favour a user mapper for `NotFoundException` it would not favour one for `Exception` which is more generic.

Now, do note that the `NotFoundExceptionMapper` only applies to the DEV mode.

We could perhaps only register it if we didn't find any user mapper that is more generic, but that would mean that the DEV mode is less useful when it comes to 404 because user mappers are likely to be less user-friendly.

**Comment by asoldano** [comment]
@ronsigal , do you have any thoughts here?

**Comment by ronsigal** [comment]
Hi @Ladicek,

I'm not following the premise here. You said you created "my own NotFoundExceptionMapper" but that it is an "implementation of ExceptionMapper<Exception>". So the JAX-RS spec says your ExceptionMapper would not got used:

```
When choosing an exception mapping provider to map an exception, an implementation MUST use the
provider whose generic type is the nearest superclass of the exception. If two or more exception providers
are applicable, the one with the highest priority MUST be chosen as described in Section 4.1.3.
```

Why not create an ExceptionMapper<NotFoundExceptionMapper> and annotate it with a @Priority higher than the one in Quarkus?

What am I missing?

-Ron

**Comment by FroMage** [comment]
Quarkus has one for `NotFoundException` (low prio, but nearest superclass), the user has one for `Exception` (high prio, but furthest superclass).

I guess the user would like his mapper to override the Quarkus one.

**Comment by Ladicek** [comment]
@ronsigal What you're suggesting is the workaround I was able to identify and use. (Fortunately, the Quarkus built-in exception mappers are `@Priority(Priorities.USER + 1)`, so I don't have to add `@Priority` myself.)

What I'd like to happen is if I define my own exception mapper (for a more general class), the Quarkus built-in exception mappers are not used. What @FroMage says, basically :-)

**Comment by ronsigal** [comment]
@Ladice, OK, I understand what you want. Given that it contradicts the JAX-RS spec, I don't see it happening without something ... extra. Here's something that could be relevant, although it's not implemented in RESTEasy 4.x yet.

In RESTEasy 3.11.0.Final (for WF 19) I implemented a "resteasy.disable.providers" parameter, which lets you do something like
```
    <context-param>
        <param-name>resteasy.disable.providers</param-name>
        <param-value>org.jboss.resteasy.plugins.providers.DefaultTextPlain,org.jboss.resteasy.plugins.providers.StringTextStar</param-value>
    </context-param>
```
which would disable those two providers. That's still pending for RESTEasy 4.x (https://issues.redhat.com/browse/RESTEASY-2475). Also, RESTEasy 4.x uses MicroProfile Config, so "resteasy.disable.providers" can be configured in lots of different ways.

So, you could disable the disrupting Quarkus ExceptionMapper. Maybe that helps?

-Ron

**Comment by Ladicek** [comment]
@ronsigal I can think of several workarounds -- your one is interesting, but still a workaround, from my perspective. I think this is something that needs to be solved between Quarkus and RESTEasy. I understand that from RESTEasy perspective, whatever Quarkus adds is part of the application, but from application developer's perspective, it is not.

**Comment by andreas-eberle** [comment]
What is the status on this issue? We just ran into it and where very confused until we found this bug report.

Is it guaranteed, that this will only happen in dev mode? And that it only happens with the NotFoundException? Or are you planning to add mappers for more Exceptions in the future or for the normal build as well?

I think this issue should be fixed and not forgotten.

**Comment by gneu77** [comment]
Just disabling all other exception mappers would save me some work (I have the simple requirement that all exceptions thrown by my application must be of type ApplicationException, hence all my implemented exceptions are derived from ApplicationException and other exceptions must be mapped to one of these ApplicationException subclasses).

But even this:
> ...an implementation MUST use the provider whose generic type is the nearest superclass of the exception...

seems not to be true:

E.g. I have a `BadRequestException` derived from `ApplicationException`. Now if I throw `BadRequestException`, not `ApplicationExceptionMapper implements ExceptionMapper<ApplicationException>` is called, but instead `ConstraintExceptionMapper implements ExceptionMapper<ConstraintViolationException>` is called (regardless of any `@Priority`), where `ConstraintViolationException` is `javax.validation.ConstraintViolationException` and is thus not derived from my `ApplicationException` class.

So it seems like I'm missing something important here...

**Comment by israelstmz** [comment]
Any news regarding this issue? We also ran into this unexpected behavior and still can't find a decent walkaround. 
We whish to declare a "catch-all" exception mapper - and log these to our DB. But any pre-defined mapper keeps overriding our generic one. We tried changing our priority but it doesn't help, probably since the more specific pre-defined mapper always "wins"...

**Comment by Shinigami92** [comment]
I also run into this problem and it cost headaches and a whole weekend
I don't only want a 404 with empty body, but we want our own body with different info in the json response like message, code and so on

The only way I now found working is to create my own Exception
```kt
package com.dermalog.myview

import javax.ws.rs.WebApplicationException
import javax.ws.rs.core.Response

class EntityNotFoundException(message: String) : WebApplicationException(message, Response.Status.NOT_FOUND)
```

But tbh this feels horrible

**Comment by geoand** [comment]
I am wondering if we should have the following special rule:

If a user provided catch-all ExceptionMapper (i.e. `ExceptionMapper<Exception>`) exists, then have it implicitly "override" the Quarkus provided `ExceptionMapper` classes, regardless of the nearest exception rule.
This would be in violation of the spec, but it does seem to be intuitively what users want. 

If we want users to explicitly opt-in to this, we could also add a custom `@CatchAll` annotation that could be used in combination with `@ServerExceptionaMapper` (and with `ExceptionaMapper` too?).

@FroMage @Ladicek WDYT?

**Comment by Shinigami92** [comment]
As a Feedback: I would be okay if there is a config like disable native exception mapper and/or like you said an annotation that needs to be added to my custom exception mapper
It just needs to be documented :)

**Comment by geoand** [comment]
Right, that's also an option :)

**Comment by andreas-eberle** [comment]
I agree, a config would be better, as it makes the change explicit instead of "magic". Also it would allow me to have a "catch all" mapper and still use the internal mappers for the standard exceptions. So it is a bit more flexible.

**Comment by famod** [comment]
I'd vote for `@Override(s)BuiltInMapper` or something like that. I find `@CatchAll` too "broad", especially if you only want to override mapping of  e.g. `NotFoundException`. (also, I already have my own `@CatchAll` for other purposes :wink:)

**Comment by geoand** [comment]
I think an annotation is better, but I'd like to hear what @FroMage and @Ladicek also have to say.

**Comment by Ladicek** [comment]
So I don't know the full set of exception mappers that Quarkus implicitly registers, but quickly looking around, some of them seem vital (`AuthenticationFailedExceptionMapper`, `UnauthorizedExceptionMapper`), while some of them look more like an attempt at convenient default (`NotFoundExceptionMapper`). My opinion is that preferring a user-provided more general exception mapper over the convenient default is _not_ a violation of the specification, because the specification doesn't expect the implementation to provide that more specific exception mapper. We would just behave as if the framework-provided mapper wasn't even there, which is perfectly fine IMHO. I don't know what to think about those "vital" exception mappers (or if they truly are vital, actually).

Adding an annotation to a user-provided exception mapper is a possible solution, but one that requires the mapper author to _know_ that the annotation exists and when it is required. That, in my opinion, makes it a half-solution at best.

**Comment by Ladicek** [comment]
That's a big _just_ :laughing:

**Comment by famod** [comment]
> Adding an annotation to a user-provided exception mapper is a possible solution, but one that requires the mapper author to _know_ that the annotation exists and when it is required. That, in my opinion, makes it a half-solution at best.

There could be a WARN message hinting at that annotation in case two mappings are detected (built-in and user-defined).

But then again the user-defined mapping could just be used automatically, as you said @Ladicek (maybe together with a DEBUG message).

**Comment by geoand** [comment]
> My opinion is that preferring a user-provided more general exception mapper over the convenient default is not a violation of the specification, because the specification doesn't expect the implementation to provide that more specific exception mapper.

Not really, because the spec says that if a `ExceptionMapper` for a specific exception exists, then it is always prefered over a mapper for one of the super types - it does not matter whether it's built-in or not, built-in or not comes into play only when there is an actual "conflict ".

**Comment by Ladicek** [comment]
Sure, but it's our choice that it exists. It doesn't have to, under conditions we are free to define, IIUC.

**Comment by geoand** [comment]
> Sure, but it's our choice that it exists. It doesn't have to, under conditions we are free to define, IIUC

True, I just understand what you are proposing, that we get rid of the existing `NotFoundExceptionMapper` altogether?

**Comment by Ladicek** [comment]
No, I wouldn't want to get rid of it _altogether_. It provides a nice HTML output, but it gets in the way in other cases. I think I would probably pretend that it doesn't exist in case the user provides a more general exception mapper.

**Comment by geoand** [comment]
> I think I would probably pretend that it doesn't exist in case the user provides a more general exception mappe

Gotcha.

**Comment by geoand** [comment]
I am still leaning on making it explicit, but I would also like to hear what @FroMage has to say

**Comment by aldettinger** [comment]
Whatever solution is chosen, there is a point that would need to be clarified.

Let's say we have a list of custom mappers, ExceptionMapper<BadRequest>, ExceptionMapper<NotFoundException>, ExceptionMapper<Exception>...

Is it true the algorithm to match an incoming exception to one of those mappers is defined by the JAX-RS specification ?As such it would not be possible for a Quarkus user to write a custom algorithm ?

**Comment by geoand** [comment]
> Is it true that the algorithm to match an incoming exception to one of those mappers is defined by the JAX-RS specification

Yes, it is. Here is what `JAX-RS 2.1` says:

```
3.3.4 Exceptions

A resource method, sub-resource method or sub-resource locator may throw any checked or unchecked
exception. An implementation MUST catch all exceptions and process them in the following order:


1. Instances of WebApplicationException and its subclasses MUST be mapped to a response as fol-
lows. If the response property of the exception does not contain an entity and an exception mapping
provider (see Section 4.4) is available for WebApplicationException or the corresponding sub-
class, an implementation MUST use the provider to create a new Response instance, otherwise the
response property is used directly. The resulting Response instance is then processed according to
Section 3.3.3.

2. If an exception mapping provider (see Section 4.4) is available for the exception or one of its super-
classes, an implementation MUST use the provider whose generic type is the nearest superclass of
the exception to create a Response instance that is then processed according to Section 3.3.3. If the
exception mapping provider throws an exception while creating a Response then return a server error
(status code 500) response to the client.

3. Unchecked exceptions and errors that have not been mapped MUST be re-thrown and allowed to
propagate to the underlying container.

4. Checked exceptions and throwables that have not been mapped and cannot be thrown directly MUST
be wrapped in a container-specific exception that is then thrown and allowed to propagate to the un-
derlying container. Servlet-based implementations MUST use ServletException as the wrapper.
JAX-WS Provider-based implementations MUST use WebServiceException as the wrapper.

Note: Items 3 and 4 allow existing container facilities (e.g. a Servlet filter or error pages) to be used to
handle the error if desired
```
